
go
print 'F1 - 27'
go

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[OMS_PO_LINE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[OMS_PO_LINE](
    [rowId] [int] IDENTITY(1,1) NOT NULL,
    [idLoad] [int] NULL,
    [OMS_PO_NBR] [numeric](10,0) NULL,
    [OMS_PO_LINE_NBR] [int] NULL,
    [VENDOR_NBR] [int] NULL,
    [VENDOR_DEPT_NBR] [int] NULL,
    [VENDOR_SEQ_NBR] [int] NULL,
    [VENDOR_STOCK_ID] [varchar](4000) NULL,
    [APPV_VNPK_ORD_QTY] [int] NULL,
    [VNPK_ORD_QTY] [int] NULL,
    [ITEM_NBR] [int] NULL,
    [VARIABLE_WT_IND] [nchar](1) NULL,
    [ORDER_DEPT_NBR] [int] NULL,
    [ACCTG_DEPT_NBR] [int] NULL,
    [ITEM1_DESC] [varchar](4000) NULL,
    [ITEM2_DESC] [varchar](4000) NULL,
    [SHLFLBL1_COLR_DESC] [varchar](4000) NULL,
    [SHLFLBL2_SIZE_DESC] [varchar](4000) NULL,
    [VNPK_CUBE_QTY] [numeric](9,3) NULL,
    [VNPK_CUBE_UOM_CD] [nchar](2) NULL,
    [VNPK_COST_AMT] [numeric](13,4) NULL,
    [VNPK_QTY] [int] NULL,
    [VNPK_WEIGHT_QTY] [numeric](11,4) NULL,
    [VNPK_WEIGHT_UOM_CD] [nchar](2) NULL,
    [WHPK_QTY] [int] NULL,
    [COMMODITY_ID] [int] NULL,
    [BUYER_USERID] [nchar](8) NULL,
    [ASSORTMENT_TYPE_CD] [int] NULL,
    [SHLF_LIFE_DAYS_QTY] [int] NULL,
    [CHANNEL_MTHD_CD] [int] NULL,
    [HAZMAT_ID] [int] NULL,
    [CAL_OTB_YEAR_NBR] [int] NULL,
    [CAL_OTB_MONTH_NBR] [int] NULL,
    [MABD_DATE] [date] NULL,
    [MABD_TIME] [time] NULL,
    [DNSB_DATE] [date] NULL,
    [DNSA_DATE] [date] NULL,
    [DNRB_DATE] [date] NULL,
    [DNRB_TIME] [time] NULL,
    [PO_EVENT_ABBR] [varchar](4000) NULL,
    [TAB_EVENT_IND] [nchar](1) NULL,
    [ORDER_GROUP_ID] [int] NULL,
    [LOAD_GROUP_ID] [int] NULL,
    [BASE_DIV_NBR] [int] NULL,
    [NET_FIRST_COST_AMT] [numeric](13,4) NULL,
    [PO_LINE_STATUS_CD] [int] NULL,
    [PO_LINE_CREATE_TS] [datetime2] NULL,
    [MANUAL_CREATE_IND] [nchar](1) NULL,
    [CREATE_USERID] [nchar](8) NULL,
    [CREATE_SYSTEM_ID] [nchar](10) NULL,
    [LAST_CHG_USERID] [nchar](8) NULL,
    [LAST_CHG_TS] [datetime2] NULL,
    [VNPK_RCV_QTY] [int] NULL,
    [RECEIVED_WGT_QTY] [numeric](11,4) NULL,
    [VNPK_NETWGT_QTY] [numeric](11,4) NULL,
    [DRUG_CONTROL_ABBR] [nchar](8) NULL,
    [WHPK_RCV_QTY] [int] NULL,
    [APPV_WHPK_ORD_QTY] [int] NULL,
    [WHPK_ORD_QTY] [int] NULL,
    [WM_OTB_YEAR_NBR] [int] NULL,
    [WM_OTB_MONTH_NBR] [int] NULL,
    [CREATE_REASON_CD] [int] NULL,
    [EDIT_REASON_CD] [int] NULL,
    [SEASONAL_IND] [nchar](1) NULL,
    [SAMPLE_PO_IND] [nchar](1) NULL,
    [LTL_IND] [nchar](1) NULL,
    [VENDOR_POOL_ID] [int] NULL,
    [FOB_PT_TYPE_CODE] [nchar](2) NULL,
    [EVENT_TYPE_CODE] [int] NULL,
    [OMS_QLTY_HLD_CD] [int] NULL,
    [PAY_FROM_SCAN_IND] [nchar](1) NULL,
    [FINELINE_NBR] [int] NULL,
    [SUBCLASS_NBR] [int] NULL,
    [VNPK_COST_UOM_CD] [nchar](2) NULL,
    [PROMOTIONAL_BUY_IND] [nchar](1) NULL,
    [BASE_UNIT_RTL_AMT] [numeric](11,2) NULL,
    [ROW_CHANGE_TS] [datetime2] NULL,
    [PALLET_TI_QTY] [int] NULL,
    [PALLET_HI_QTY] [int] NULL,
    [ON_HAND_DAYS_QTY] [int] NULL,
    [POP_PRIORITY_NBR] [int] NULL,
    [STORAGE_AMT] [numeric](9,4) NULL,
    [HANDLING_AMT] [numeric](9,4) NULL,
    [FREIGHT_FACTOR_PCT] [numeric](5,4) NULL,
    [FREIGHT_FACTOR_AMT] [numeric](15,4) NULL) END
	--[FREIGHT_FACTOR_AMT] [nchar](20) NULL) END



GO


