//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apcm.Service.Lote {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoteScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoteScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apcm.Service.Lote.LoteScripts", typeof(LoteScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Lote.ConfirmarLote
        ///
        ///Update Lote Set DhRetorno = GETDATE(), StatusRetorno = &apos;Lote processado.&apos; Where NumeroLote = @NumeroLote.
        /// </summary>
        internal static string ConfirmarLote {
            get {
                return ResourceManager.GetString("ConfirmarLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Lote.PesquisaLote
        ///
        ////*
        ///	Declare 
        ///		@Usuario varchar(100) = null --&apos;vn05rzj&apos;
        ///		, @NumeroLote varchar(20) = &apos;20201030160813099&apos;
        ///		, @CodOrigem varchar(5) = &apos;&apos; -- empty todos, Sad, Sams, Novo.
        ///		, @DataDe datetime = null
        ///		, @DataAte datetime = null
        ///		, @StatusLote int = -1 -- 1 = Processado, 0 = Não Processado ou Erro, -1 = todos -- @StatusLote 0 trava @StatusItem em -01
        ///		, @StatusItem varchar(255) = &apos;-01&apos; -- -01 todos, -02 Ok, -03 NOk, xxx - demais (distinct das ultimas msgs)
        ///--*/
        ///
        ///Declare @H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConsultaLote {
            get {
                return ResourceManager.GetString("ConsultaLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Lote.PesquisaLoteExportacao
        ///
        ////*
        ///	Declare 
        ///		@Usuario varchar(100) = null --&apos;vn05rzj&apos;
        ///		, @NumeroLote varchar(20) = null --&apos;20200909153749257&apos;
        ///		, @CodOrigem varchar(5) = &apos;&apos; -- empty todos, Sad ou Sams.
        ///		, @DataDe datetime = null
        ///		, @DataAte datetime null
        ///		, @StatusLote int = -1 -- 1 = Processado, 0 = Não Processado ou Erro, -1 = todos -- @StatusLote 0 trava @StatusItem em -01
        ///		, @StatusItem varchar(255) = &apos;-01&apos; -- -01 todos, -02 Ok, -03 NOk, xxx - demais (distinct das ultimas msgs)
        ///		, @St [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConsultaLoteExportacao {
            get {
                return ResourceManager.GetString("ConsultaLoteExportacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Lote.ContagemConsultaLote
        ///
        ////*
        ///	Declare 
        ///		@Usuario varchar(100) = null --&apos;vn05rzj&apos;
        ///		, @NumeroLote varchar(20) = null -- &apos;20200828090446677&apos;
        ///		, @CodOrigem varchar(5) = &apos;&apos; -- empty todos, Sad, Sams, Novo.
        ///		, @DataDe datetime = null
        ///		, @DataAte datetime null
        ///		, @StatusLote int = -1 -- 1 = Processado, 0 = Não Processado ou Erro, -1 = todos -- @StatusLote 0 trava @StatusItem em -01
        ///		, @StatusItem varchar(255) = &apos;-01&apos; -- -01 todos, -02 Ok, -03 NOk, xxx - demais (distinct das ultimas msgs)
        ///--*/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContagemConsultaLote {
            get {
                return ResourceManager.GetString("ContagemConsultaLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Lote Incluir
        ///
        ////*
        ///	Declare @IdCarrinho int, @NumeroLote varchar(20)
        ///--*/
        ///
        ///if not exists ( select * From Lote Where NumeroLote = @NumeroLote )
        ///Begin
        ///	Insert Into Lote (IdCarrinho, DhEnvio, NumeroLote) Values (@IdCarrinho, GETDATE(), @NumeroLote)
        ///End.
        /// </summary>
        internal static string Incluir {
            get {
                return ResourceManager.GetString("Incluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Lote.LotesPendentes
        ///
        ///Select
        ///	l.IdLote
        ///	, l.IdCarrinho
        ///	, l.DhEnvio
        ///	, l.NumeroLote
        ///	, l.DhRetorno
        ///	, l.StatusRetorno
        ///
        ///	, ISNULL(c.CodSistema, &apos;Atacado&apos;) as CodSistema
        ///From
        ///	Lote as l
        ///	Inner Join Carrinho as c
        ///		on c.IdCarrinho = l.IdCarrinho
        ///Where
        ///	DhRetorno is null
        ///	--l.NumeroLote = &apos;20201215142335818&apos;.
        /// </summary>
        internal static string LotesPendentes {
            get {
                return ResourceManager.GetString("LotesPendentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Lote.ObterStatusItem
        ///
        ////*
        ///	Declare 
        ///		@CodOrigem varchar(10) = &apos;&apos;
        ///		, @DataDe datetime = null
        ///		, @DataAte datetime = null
        ///--*/
        ///
        ///Declare @tblStatusItem as Table ([CodStatusItem] varchar(255), [StatusItem] varchar(255))
        ///
        ///Insert Into @tblStatusItem Values (&apos;-01&apos;, &apos;Todos&apos;), (&apos;-02&apos;, &apos;Acerto&apos;), (&apos;-03&apos;, &apos;Erro&apos;)
        ///
        ///SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
        ///
        ///;with
        ///cteUltimoEnvio as (
        ///	Select 
        ///		cil.IdCarrinhoItem, Max(l.DhEnvio) as DhUltimoEnvio
        ///	From 
        ///		Lote as l
        ///		Inner Join CarrinhoIt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObterStatusItem {
            get {
                return ResourceManager.GetString("ObterStatusItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Lote.RegistrarCarrinhoDessinc
        ///
        ////*
        ///	Declare @DessincRetorno varchar(max) = &apos;{&quot;NumeroLote&quot;:&quot;20201126163600000&quot;,&quot;Produtos&quot;:[{&quot;ProdutoNbr&quot;: &quot;1&quot;, &quot;CodRetorno&quot;:&quot;000&quot;, &quot;MsgRetorno&quot;:&quot;Ok&quot;}, {&quot;ProdutoNbr&quot;: &quot;2&quot;, &quot;CodRetorno&quot;:&quot;001&quot;, &quot;MsgRetorno&quot;:&quot;Erro&quot;}]}&apos;
        ///--*/
        ///
        ///Declare @NumeroLote varchar(20)
        ///Select @NumeroLote = NumeroLote From
        ///	openjson(@DessincRetorno) with (
        ///		NumeroLote varchar(20) &apos;$.NumeroLote&apos;
        ///	);
        ///
        ///Declare @Produtos as table (ProdutoNbr varchar(50), CodRetorno varchar(10), MsgRetorno varchar(255 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegistrarCarrinhoDessinc {
            get {
                return ResourceManager.GetString("RegistrarCarrinhoDessinc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Lote.InserirCarrinhoItemLote
        ///
        ////*
        ///	Declare @IdCarrinhoItem int, @NumeroLote varchar(20), @CodRetorno varchar(10), @StatusRetorno varchar(255), @Filial int
        ///--*/
        ///
        ///Insert Into CarrinhoItemLote ( IdCarrinhoItem, IdLote, CodRetorno, StatusRetorno, Filial )
        ///	Select
        ///		@IdCarrinhoItem, l.IdLote, @CodRetorno, @StatusRetorno, @Filial
        ///	From
        ///		Lote as l
        ///		Left Join CarrinhoItemLote as cil on cil.IdLote = l.IdLote And cil.IdCarrinhoItem = @IdCarrinhoItem
        ///	Where 
        ///		l.NumeroLote = @NumeroLote
        ///		And cil.IdC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegistrarCarrinhoItemLote {
            get {
                return ResourceManager.GetString("RegistrarCarrinhoItemLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Lote.RegistrarStatusRetornoErro
        ///
        ///Update Lote Set StatusRetorno = @StatusRetorno Where NumeroLote = @NumeroLote.
        /// </summary>
        internal static string RegistrarStatusRetornoErro {
            get {
                return ResourceManager.GetString("RegistrarStatusRetornoErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Lote UltimoLote
        ///
        ////*
        ///	Declare @IdCarrinho int = 16
        ///--*/
        ///
        ///;with 
        ///cteUltimoEnvio as ( Select IdCarrinho, Max(DhEnvio) as DhUltimoEnvio From Lote Group By IdCarrinho )
        ///
        ///Select 
        ///	l.*
        ///From
        ///	cteUltimoEnvio as ur 
        ///	Inner Join Lote as l on l.IdCarrinho = ur.IdCarrinho And l.DhEnvio = ur.DhUltimoEnvio
        ///Where
        ///	l.IdCarrinho = @IdCarrinho
        ///.
        /// </summary>
        internal static string UltimoLote {
            get {
                return ResourceManager.GetString("UltimoLote", resourceCulture);
            }
        }
    }
}
