//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apcm.Service.Cross {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CrossScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CrossScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apcm.Service.Cross.CrossScripts", typeof(CrossScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Cross.AtualizarDessincSadReport
        ///
        ///Declare @tblProdutoDessinc as table (ProdutoNbr int) -- Produtos dessincronizados.
        ///
        ///Insert Into @tblProdutoDessinc
        ///	Select Distinct
        ///		cd.ProdutoNbr--, &apos;SAD&apos; as TipoDessinc
        ///	From
        ///		CarrinhoDessinc as cd
        ///		Left Join XREF_BR_IF_ITEM_LOG as l
        ///			on l.SAD_CODPRODU = cd.ProdutoNbr
        ///			And isnull(l.DESSINC_ITEM, l.DESSINC_PRODUTO) = 1
        ///	Where
        ///		cd.CodRetorno = &apos;000&apos;
        ///		And l.XREF_BR_IF_ITEM_ID is null
        ///
        ///Insert Into @tblProdutoDessinc
        ///	Select Distinct
        ///		SAD_CODPRODU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AtualizarDessincSadReport {
            get {
                return ResourceManager.GetString("AtualizarDessincSadReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Cross.DessincLocal
        ///
        ////*
        ///	Declare @DessincLocal varchar(max) = &apos;{&quot;Login&quot;:&quot;gsilv17&quot;,&quot;Crosses&quot;:[3384]}&apos;
        ///--*/
        ///
        ///Declare @Login varchar(10)
        ///Select @Login = Login From
        ///	openjson(@DessincLocal) with (
        ///		Login varchar(10) &apos;$.Login&apos;
        ///	);
        ///
        ///Declare @Crosses as table (IdCross int)
        ///Insert Into @Crosses
        ///	Select IdCross From
        ///		openjson(@DessincLocal) with (
        ///			Crosses nvarchar(max) &apos;$.Crosses&apos; as json
        ///		)
        ///		Outer Apply openjson(Crosses) with (
        ///			IdCross int &apos;$&apos;
        ///		);
        ///
        ///Declare @DhRetorno datetime
        ///Set [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DessincLocal {
            get {
                return ResourceManager.GetString("DessincLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Cross.ExisteLog
        ///
        ////*
        ///	Declare @ProdutoNbr int = 117368
        ///--*/
        ///Declare @Existe bit
        ///
        ///If exists (Select * From XREF_BR_IF_ITEM_LOG as x Where x.sad_codprodu = @ProdutoNbr)
        ///	Set @Existe = 1
        ///Else
        ///	Set @Existe = 0
        ///
        ///Select @Existe as existe.
        /// </summary>
        internal static string ExisteLog {
            get {
                return ResourceManager.GetString("ExisteLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Cross.Localizar
        ///
        ////*
        ///	Declare @ProdutoNbr int = 117368
        ///--*/
        ///
        ///
        ///Select 
        ///	x.XREF_BR_IF_ITEM_ID as IdCross
        ///	, x.SAMS_ITEM_ID as ItemNbr
        ///	, x.SAD_CODPRODU as ProdutoNbr
        ///	, x.IDCARRINHOITEM as IdCarrinhoItem
        ///	, x.ITEM_DESC as ProdutoDesc
        ///	, u.Nome
        ///	, ci.EmEdicao
        ///From
        ///	XREF_BR_IF_ITEM as x
        ///	Inner Join CarrinhoItem as ci
        ///		on ci.IdCarrinhoItem = x.IDCARRINHOITEM
        ///	Inner Join Carrinho as c
        ///		on c.IdCarrinho = ci.IdCarrinho
        ///	Inner Join TSamsF3User as u
        ///		on u.[Login] = c.[Login]
        ///Where
        ///	x.sad_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Localizar {
            get {
                return ResourceManager.GetString("Localizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Cross.ObterDessincSadReport
        ///
        ///Select
        ///	IdDessincSadReport, NumeroLote, IdCarrinhoItem
        ///From
        ///	DessincSadReport
        ///Where
        ///	NumeroLoteSadReport is null.
        /// </summary>
        internal static string ObterDessincSadReport {
            get {
                return ResourceManager.GetString("ObterDessincSadReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Cross.PesquisaDessinc
        ///
        ////*
        ///	Declare @ProdutoNbr int, @ItemNbr int
        ///--*/
        ///
        ///Declare @tblUltimoRetorno as table (ProdutoNbr int, DhRetorno datetime)
        ///
        ///Insert into @tblUltimoRetorno
        ///	Select
        ///		cd.ProdutoNbr, Max(DhRetorno) as DhRetorno
        ///	From
        ///		CarrinhoDessinc as cd
        ///	Where
        ///		( @ProdutoNbr is null Or cd.ProdutoNbr = @ProdutoNbr )
        ///	Group By 
        ///		cd.ProdutoNbr
        ///
        ///Select 
        ///	cd.ProdutoNbr as ProdutoNbr
        ///	, null as ItemNbr
        ///	, Case
        ///		When cd.CodRetorno = &apos;000&apos; Then &apos;SAD&apos;
        ///		Else &apos;Erro (&apos; + cd.MsgRetorno + [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PesquisaDessinc {
            get {
                return ResourceManager.GetString("PesquisaDessinc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Cross.RegistrarCross
        ///
        ////*
        ///	Declare @IdCarrinhoItem int = 209384, @CodProd int = 127399, @Cean varchar(20) = &apos;789114910556&apos;, @Tean int = 1, @Eandg int = 4
        ///--*/
        ///
        ///Declare @CodOrigem varchar(10)
        ///
        ///Select @CodOrigem = Isnull(CodOrigem, &apos;Sams&apos;) From Carrinho as c Inner Join CarrinhoItem as ci on ci.IdCarrinho = c.IdCarrinho Where ci.IdCarrinhoItem = @IdCarrinhoItem
        ///
        ///if @CodOrigem = &apos;Sams&apos;
        ///	Begin
        ///
        ///		Declare @CodItem int
        ///		Select @CodItem = item_nbr From CarrinhoItem as ci Where ci.IdCarrinhoItem = @ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegistrarCross {
            get {
                return ResourceManager.GetString("RegistrarCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Cross.RegistrarLoteDessincSadReport
        ///
        ////*
        ///	Declare @Dados varchar(4000) = &apos;{&quot;Ids&quot;:[1, 2, 3],&quot;NumeroLote&quot;:&quot;123&quot;}&apos;
        ///--*/
        ///
        ///Declare @Ids as table (Id int)
        ///Declare	@NumeroLote varchar(20)
        ///
        ///Insert Into @Ids
        ///	Select Id From
        ///		openjson(@Dados) with (
        ///			Ids nvarchar(max) &apos;$.Ids&apos; as json
        ///		)
        ///		Outer Apply openjson(Ids) with (
        ///			Id int &apos;$&apos;
        ///		);
        ///
        ///Select @NumeroLote = NumeroLote From
        ///	openjson(@Dados) with (
        ///		NumeroLote varchar(20) &apos;$.NumeroLote&apos;
        ///	);
        ///
        ///Update DessincSadReport Set NumeroLoteSadRe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegistrarLoteDessincSadReport {
            get {
                return ResourceManager.GetString("RegistrarLoteDessincSadReport", resourceCulture);
            }
        }
    }
}
