//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apcm.Service.Log {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apcm.Service.Log.LogScripts", typeof(LogScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Log.RegistrarLog
        ///
        ////*
        ///	Declare @IdCarrinho int, @NumeroLote varchar(20)
        ///--*/
        ///
        ///Insert Into ApcmLog (Emissor, Tipo, Dh, Mensagem) Values (@Emissor, @Tipo, GETDATE(), @Mensagem).
        /// </summary>
        internal static string RegistrarLog {
            get {
                return ResourceManager.GetString("RegistrarLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Log.RegistrarLog
        ///
        ////*
        ///	Declare @IdCarrinho int, @NumeroLote varchar(20)
        ///--*/
        ///
        ///Insert Into ApcmLog (Emissor, Tipo, Dh, Mensagem) Values (@Emissor, @Tipo, GETDATE(), @Mensagem).
        /// </summary>
        internal static string RegistrarLogFixo {
            get {
                return ResourceManager.GetString("RegistrarLogFixo", resourceCulture);
            }
        }
    }
}
