
go
print 'F3 - 08 - XREF_BR_IF_ITEM'
go

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[XREF_BR_IF_ITEM]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[XREF_BR_IF_ITEM](
	[XREF_BR_IF_ITEM_ID] [int] IDENTITY(1,1) NOT NULL,
	[SAMS_ITEM_ID] [int] NULL,
	[SAMS_UPC_NBR] [numeric](18, 0) NULL,
	[SAMS_VENDOR_NBR] [varchar](9) NULL,
	[SAMS_PLU_NBR] [int] NULL,
	[SAD_CODPRODU] [int] NULL,
	[SAD_CODIGO_EAN] [numeric](18, 0) NULL,
	[IDCARRINHOITEM] [int] NULL,
	[ITEM_DESC] [varchar](300) NULL,
	[STATUS_ITEM] [char](1) NULL,
	[QTDEPACK] [int] NULL,
	[MULTIPACK] [char](1) NULL,
	[UPC_REAL] [numeric](18, 0) NULL,
	[DT_ALTERACAO] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[XREF_BR_IF_ITEM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

