//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apcm.Service.RetornoSAD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SearchScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apcm.Service.RetornoSAD.SearchScripts", typeof(SearchScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;&apos; AS CODIGO, &apos;Todos&apos; AS MENSAGEM
        ///UNION
        ///SELECT CODRETORNO+&apos;|&apos;+UPPER(MSGRETORNO) AS CODIGO, CODRETORNO + &apos; - &apos; + UPPER(MSGRETORNO) AS MENSAGEM FROM STATUSRETORNOFEP 
        ///ORDER BY 1.
        /// </summary>
        internal static string SearchFiltroStatus {
            get {
                return ResourceManager.GetString("SearchFiltroStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.CODRETORNO+&apos; - &apos;+UPPER(CARITLT.STATUSRETORNO), &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD
        ///	,ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem
        ///	,ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor
        ///	,ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor
        ///	,CAST(ISNULL(CARIT.codCategoria, &apos;0&apos;) AS INT) AS CodigoCategoria [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturn {
            get {
                return ResourceManager.GetString("SearchReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.CODRETORNO+&apos; - &apos;+UPPER(CARITLT.STATUSRETORNO), &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD
        ///	,ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem
        ///	,ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor
        ///	,ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor
        ///	,CAST(ISNULL(CARIT.codCategoria, &apos;0&apos;) AS INT) AS CodigoCategoria [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnByLogin {
            get {
                return ResourceManager.GetString("SearchReturnByLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.CODRETORNO+&apos; - &apos;+UPPER(CARITLT.STATUSRETORNO), &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD
        ///	,ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem
        ///	,ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor
        ///	,ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor
        ///	,CAST(ISNULL(CARIT.codCategoria, &apos;0&apos;) AS INT) AS CodigoCategoria [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnByLote {
            get {
                return ResourceManager.GetString("SearchReturnByLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.CODRETORNO+&apos; - &apos;+UPPER(CARITLT.STATUSRETORNO), &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD
        ///	,ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem
        ///	,ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor
        ///	,ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor
        ///	,CAST(ISNULL(CARIT.codCategoria, &apos;0&apos;) AS INT) AS CodigoCategoria [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnByMsgRetorno {
            get {
                return ResourceManager.GetString("SearchReturnByMsgRetorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.CODRETORNO+&apos; - &apos;+UPPER(CARITLT.STATUSRETORNO), &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD
        ///	,ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem
        ///	,ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor
        ///	,ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor
        ///	,CAST(ISNULL(CARIT.codCategoria, &apos;0&apos;) AS INT) AS CodigoCategoria [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnErrorNoFilters {
            get {
                return ResourceManager.GetString("SearchReturnErrorNoFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.CODRETORNO+&apos; - &apos;+UPPER(CARITLT.STATUSRETORNO), &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD
        ///	,ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem
        ///	,ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor
        ///	,ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor
        ///	,CAST(ISNULL(CARIT.codCategoria, &apos;0&apos;) AS INT) AS CodigoCategoria [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnFull {
            get {
                return ResourceManager.GetString("SearchReturnFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.CODRETORNO+&apos; - &apos;+UPPER(CARITLT.STATUSRETORNO), &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD
        ///	,ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem
        ///	,ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor
        ///	,ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor
        ///	,CAST(ISNULL(CARIT.codCategoria, &apos;0&apos;) AS INT) AS CodigoCategoria [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnMsgRetornoLogin {
            get {
                return ResourceManager.GetString("SearchReturnMsgRetornoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.CODRETORNO+&apos; - &apos;+UPPER(CARITLT.STATUSRETORNO), &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD
        ///	,ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem
        ///	,ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor
        ///	,ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor
        ///	,CAST(ISNULL(CARIT.codCategoria, &apos;0&apos;) AS INT) AS CodigoCategoria [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnMsgRetoroLote {
            get {
                return ResourceManager.GetString("SearchReturnMsgRetoroLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.CODRETORNO+&apos; - &apos;+UPPER(CARITLT.STATUSRETORNO), &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD
        ///	,ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem
        ///	,ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor
        ///	,ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor
        ///	,CAST(ISNULL(CARIT.codCategoria, &apos;0&apos;) AS INT) AS CodigoCategoria [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnNoFilters {
            get {
                return ResourceManager.GetString("SearchReturnNoFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.CODRETORNO+&apos; - &apos;+UPPER(CARITLT.STATUSRETORNO), &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD
        ///	,ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem
        ///	,ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor
        ///	,ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor
        ///	,CAST(ISNULL(CARIT.codCategoria, &apos;0&apos;) AS INT) AS CodigoCategoria [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnNoFilters1 {
            get {
                return ResourceManager.GetString("SearchReturnNoFilters1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	CAR.IDCARRINHO, 
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	ISNULL(CARITLT.CODRETORNO,&apos;&apos;) AS CodErro,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.CODRETORNO+&apos; - &apos;+UPPER(CARITLT.STATUSRETORNO), &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CARITLT.FILIAL,&apos;&apos;) AS Filial, 
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD,
        ///	ISNULL(CARIT.item_nbr, &apos;0&apos;) AS CodItemLink,
        ///	ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem,	
        ///	ISNUL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnStatusItemError {
            get {
                return ResourceManager.GetString("SearchReturnStatusItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	CAR.IDCARRINHO, 
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	ISNULL(CARITLT.CODRETORNO,&apos;&apos;) AS CodErro,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.CODRETORNO+&apos; - &apos;+UPPER(CARITLT.STATUSRETORNO), &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CARITLT.FILIAL,&apos;&apos;) AS Filial, 
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD,
        ///	ISNULL(CARIT.item_nbr, &apos;0&apos;) AS CodItemLink,
        ///	ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem,	
        ///	ISNUL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnStatusItemErrorByLogin {
            get {
                return ResourceManager.GetString("SearchReturnStatusItemErrorByLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	CAR.IDCARRINHO, 
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	ISNULL(CARITLT.CODRETORNO,&apos;&apos;) AS CodErro,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.CODRETORNO+&apos; - &apos;+UPPER(CARITLT.STATUSRETORNO), &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CARITLT.FILIAL,&apos;&apos;) AS Filial, 
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD,
        ///	ISNULL(CARIT.item_nbr, &apos;0&apos;) AS CodItemLink,
        ///	ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem,	
        ///	ISNUL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnStatusItemErrorByLote {
            get {
                return ResourceManager.GetString("SearchReturnStatusItemErrorByLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	CAR.IDCARRINHO, 
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	ISNULL(CARITLT.CODRETORNO,&apos;&apos;) AS CodErro,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.CODRETORNO+&apos; - &apos;+UPPER(CARITLT.STATUSRETORNO), &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CARITLT.FILIAL,&apos;&apos;) AS Filial, 
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD,
        ///	ISNULL(CARIT.item_nbr, &apos;0&apos;) AS CodItemLink,
        ///	ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem,	
        ///	ISNUL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnStatusItemErrorByMsgRetorno {
            get {
                return ResourceManager.GetString("SearchReturnStatusItemErrorByMsgRetorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	CAR.IDCARRINHO, 
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	ISNULL(CARITLT.CODRETORNO,&apos;&apos;) AS CodErro,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.CODRETORNO+&apos; - &apos;+UPPER(CARITLT.STATUSRETORNO), &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CARITLT.FILIAL,&apos;&apos;) AS Filial, 
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD,
        ///	ISNULL(CARIT.item_nbr, &apos;0&apos;) AS CodItemLink,
        ///	ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem,	
        ///	ISNUL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnStatusItemErrorFull {
            get {
                return ResourceManager.GetString("SearchReturnStatusItemErrorFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	CAR.IDCARRINHO, 
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	ISNULL(CARITLT.CODRETORNO,&apos;&apos;) AS CodErro,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.CODRETORNO+&apos; - &apos;+UPPER(CARITLT.STATUSRETORNO), &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CARITLT.FILIAL,&apos;&apos;) AS Filial, 
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD,
        ///	ISNULL(CARIT.item_nbr, &apos;0&apos;) AS CodItemLink,
        ///	ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem,	
        ///	ISNUL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnStatusItemErrorMsgRetornoLogin {
            get {
                return ResourceManager.GetString("SearchReturnStatusItemErrorMsgRetornoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	CAR.IDCARRINHO, 
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	ISNULL(CARITLT.CODRETORNO,&apos;&apos;) AS CodErro,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.CODRETORNO+&apos; - &apos;+UPPER(CARITLT.STATUSRETORNO), &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CARITLT.FILIAL,&apos;&apos;) AS Filial, 
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD,
        ///	ISNULL(CARIT.item_nbr, &apos;0&apos;) AS CodItemLink,
        ///	ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem,	
        ///	ISNUL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnStatusItemErrorMsgRetornoLote {
            get {
                return ResourceManager.GetString("SearchReturnStatusItemErrorMsgRetornoLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CARIT.item_nbr, &apos;0&apos;) AS CodItemLink,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD,
        ///	ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem,	
        ///	ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor,
        ///	ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor,
        ///	ISNULL(CARIT.codCategoria, &apos;&apos;) AS CodigoCategoria,
        ///	ISNULL(CARIT.DescrCategoria, &apos;&apos;) AS DescCategoria,
        ///	ISNULL(CARIT.codSubcategoria, &apos;&apos;) AS CodigoSubCategoria,
        ///	ISNULL(CARIT.DescrSubCategoria, &apos;&apos;) DescSubCategoria
        ///	,CONVERT(VARCHAR(10),ISNULL(LT.DhE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnStatusItemSuccess {
            get {
                return ResourceManager.GetString("SearchReturnStatusItemSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CARIT.item_nbr, &apos;0&apos;) AS CodItemLink,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD,
        ///	ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem,	
        ///	ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor,
        ///	ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor,
        ///	ISNULL(CARIT.codCategoria, &apos;&apos;) AS CodigoCategoria,
        ///	ISNULL(CARIT.DescrCategoria, &apos;&apos;) AS DescCategoria,
        ///	ISNULL(CARIT.codSubcategoria, &apos;&apos;) AS CodigoSubCategoria,
        ///	ISNULL(CARIT.DescrSubCategoria, &apos;&apos;) DescSubCategoria
        ///	,CONVERT(VARCHAR(10),ISNULL(LT.DhE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnStatusItemSuccessByLogin {
            get {
                return ResourceManager.GetString("SearchReturnStatusItemSuccessByLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CARIT.item_nbr, &apos;0&apos;) AS CodItemLink,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD,
        ///	ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem,	
        ///	ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor,
        ///	ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor,
        ///	ISNULL(CARIT.codCategoria, &apos;&apos;) AS CodigoCategoria,
        ///	ISNULL(CARIT.DescrCategoria, &apos;&apos;) AS DescCategoria,
        ///	ISNULL(CARIT.codSubcategoria, &apos;&apos;) AS CodigoSubCategoria,
        ///	ISNULL(CARIT.DescrSubCategoria, &apos;&apos;) DescSubCategoria
        ///	,CONVERT(VARCHAR(10),ISNULL(LT.DhE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnStatusItemSuccessByLote {
            get {
                return ResourceManager.GetString("SearchReturnStatusItemSuccessByLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CARIT.item_nbr, &apos;0&apos;) AS CodItemLink,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD,
        ///	ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem,	
        ///	ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor,
        ///	ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor,
        ///	ISNULL(CARIT.codCategoria, &apos;&apos;) AS CodigoCategoria,
        ///	ISNULL(CARIT.DescrCategoria, &apos;&apos;) AS DescCategoria,
        ///	ISNULL(CARIT.codSubcategoria, &apos;&apos;) AS CodigoSubCategoria,
        ///	ISNULL(CARIT.DescrSubCategoria, &apos;&apos;) DescSubCategoria
        ///	,CONVERT(VARCHAR(10),ISNULL(LT.DhE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnStatusItemSuccessByMsgRetorno {
            get {
                return ResourceManager.GetString("SearchReturnStatusItemSuccessByMsgRetorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CARIT.item_nbr, &apos;0&apos;) AS CodItemLink,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD,
        ///	ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem,	
        ///	ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor,
        ///	ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor,
        ///	ISNULL(CARIT.codCategoria, &apos;&apos;) AS CodigoCategoria,
        ///	ISNULL(CARIT.DescrCategoria, &apos;&apos;) AS DescCategoria,
        ///	ISNULL(CARIT.codSubcategoria, &apos;&apos;) AS CodigoSubCategoria,
        ///	ISNULL(CARIT.DescrSubCategoria, &apos;&apos;) DescSubCategoria
        ///	,CONVERT(VARCHAR(10),ISNULL(LT.DhE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnStatusItemSuccessFull {
            get {
                return ResourceManager.GetString("SearchReturnStatusItemSuccessFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CARIT.item_nbr, &apos;0&apos;) AS CodItemLink,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD,
        ///	ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem,	
        ///	ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor,
        ///	ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor,
        ///	ISNULL(CARIT.codCategoria, &apos;&apos;) AS CodigoCategoria,
        ///	ISNULL(CARIT.DescrCategoria, &apos;&apos;) AS DescCategoria,
        ///	ISNULL(CARIT.codSubcategoria, &apos;&apos;) AS CodigoSubCategoria,
        ///	ISNULL(CARIT.DescrSubCategoria, &apos;&apos;) DescSubCategoria
        ///	,CONVERT(VARCHAR(10),ISNULL(LT.DhE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnStatusItemSuccessMsgRetornoLogin {
            get {
                return ResourceManager.GetString("SearchReturnStatusItemSuccessMsgRetornoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CARIT.item_nbr, &apos;0&apos;) AS CodItemLink,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD,
        ///	ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem,	
        ///	ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor,
        ///	ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor,
        ///	ISNULL(CARIT.codCategoria, &apos;&apos;) AS CodigoCategoria,
        ///	ISNULL(CARIT.DescrCategoria, &apos;&apos;) AS DescCategoria,
        ///	ISNULL(CARIT.codSubcategoria, &apos;&apos;) AS CodigoSubCategoria,
        ///	ISNULL(CARIT.DescrSubCategoria, &apos;&apos;) DescSubCategoria
        ///	,CONVERT(VARCHAR(10),ISNULL(LT.DhE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnStatusItemSuccessMsgRetornoLote {
            get {
                return ResourceManager.GetString("SearchReturnStatusItemSuccessMsgRetornoLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	ISNULL(CAR.Login, &apos;&apos;)AS Usuario,
        ///	CASE WHEN LT.StatusRetorno IS NULL OR LT.StatusRetorno = &apos;&apos; THEN 
        ///		&apos;Não Processado&apos;
        ///	ELSE
        ///		ISNULL(CARITLT.StatusRetorno, &apos;Não Processado&apos;) 
        ///	END AS StatusRetorno,
        ///	ISNULL(CITEM.SAD_CODPRODU, &apos;0&apos;) AS CodProdutoSAD
        ///	,ISNULL(CARIT.item1_desc, &apos;&apos;) AS DescricaoItem
        ///	,ISNULL(CARIT.vendor_nbr, &apos;&apos;) AS CodVendor
        ///	,ISNULL(CARIT.DescrVendor, &apos;&apos;) AS DescVendor
        ///	,CAST(ISNULL(CARIT.codCategoria, &apos;0&apos;) AS INT) AS CodigoCategoria
        ///	,ISNULL(CARIT.DescrCategoria, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchReturnSuccessNoFilters {
            get {
                return ResourceManager.GetString("SearchReturnSuccessNoFilters", resourceCulture);
            }
        }
    }
}
