//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apcm.Service.Carrinho {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CarrinhoScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CarrinhoScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apcm.Service.Carrinho.CarrinhoScripts", typeof(CarrinhoScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Carrinho.AtualizarCarrinho
        ///
        ////*
        ///	Declare @Guid varchar(60), @IdCarrinho int
        ///--*/
        ///
        ///
        ///Update ci Set
        ///  
        ///  ci.DhUltimaImportacaoTemplate = GETDATE()
        ///, ci.DhUltimaAlteracao = GETDATE()
        ///, ci.ValidacaoTemplate = null
        ///, {0}	
        ///
        ///From
        ///	CarrinhoItem as ci
        ///	Inner Join CarrinhoItemBulk as b on
        ///		b.IdCarrinhoItem = ci.IdCarrinhoItem
        ///		And b.IdCarrinho = ci.IdCarrinho
        ///Where
        ///	b.[Guid] = @Guid
        ///	And ci.IdCarrinho = @IdCarrinho	
        ///	And ci.EmEdicao = 1.
        /// </summary>
        internal static string AtualizarCarrinho {
            get {
                return ResourceManager.GetString("AtualizarCarrinho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Carrinho AtualizarDescrEstrutura
        ///
        ////*
        ///	Declare @IdCarrinho int = 15
        ///--*/
        ///
        ///Update CarrinhoItem Set
        ///	  SamsCodDepartamento = x.N3WM_DEPTOID
        ///	, SamsDescrDepartamento = x.N3WM_DEPTO
        ///	, DescrSecao = x.N4SAD_SECAO
        ///	, DescrLinha = x.N5SAD_LINHA 
        ///	, DescrSublinha = x.N6SAD_SUBLINHA
        ///From
        ///	CarrinhoItem as ci
        ///	Inner Join SAD_ITEM_PRATELEIRA as p on p.item_nbr = ci.item_nbr
        ///	Left  Join IF_HIERARCHY_XREF_SAMS as x on 
        ///		x.N4SAD_SECAOID = p.Secao
        ///		And x.N5SAD_LINHAID = p.Linha
        ///		And x.N6SAD_SUBLINHAI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AtualizarDescrEstrutura {
            get {
                return ResourceManager.GetString("AtualizarDescrEstrutura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Carrinho.AtualizarValidacaoTemplate
        ///
        ////*
        ///	Declare @Guid varchar(60), @IdCarrinho int
        ///--*/
        ///
        ///Update ci Set
        ///	  ci.DhUltimaImportacaoTemplate = GETDATE()
        ///	, ci.DhUltimaAlteracao = GETDATE()
        ///	, ci.ValidacaoTemplate = b.ValidacaoTemplate
        ///From
        ///	CarrinhoItem as ci
        ///	Inner Join CarrinhoItemBulk as b on
        ///		b.IdCarrinhoItem = ci.IdCarrinhoItem
        ///		And b.IdCarrinho = ci.IdCarrinho
        ///Where
        ///	b.[Guid] = @Guid
        ///	And ci.IdCarrinho = @IdCarrinho	
        ///	And ci.EmEdicao = 1.
        /// </summary>
        internal static string AtualizarValidacaoTemplate {
            get {
                return ResourceManager.GetString("AtualizarValidacaoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarrinhoDataLoad.
        /// </summary>
        internal static string CarrinhoDataLoad {
            get {
                return ResourceManager.GetString("CarrinhoDataLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Carrinho.CarrinhosDisponiveis
        ///
        ////*
        ///Declare @Login varchar(10) = &apos;r0macar&apos;, @CodOrigem varchar(5) = &apos;Sams&apos;
        ///--*/
        ///
        ///SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
        ///
        ///Select
        ///	c.IdCarrinho as [Key], 
        ///	&apos;#&apos; + format(c.IdCarrinho, &apos;N0&apos;, &apos;pt-br&apos;) 
        ///	+ &apos; - &apos; + 
        ///	format(c.DhCriacao, &apos;dd/MM/yy&apos;) 
        ///	+ &apos; - &apos; + 
        ///	format(Count(1), &apos;N0&apos;, &apos;pt-br&apos;) + 
        ///		Case 
        ///			When Count(1) = 1 Then 
        ///				Case 
        ///					When c.CodOrigem = &apos;Sad&apos; Then &apos; Produto Pendente&apos;
        ///					When c.CodOrigem = &apos;Novo&apos; Then &apos; Produto Novo&apos;
        ///					E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CarrinhosDisponiveis {
            get {
                return ResourceManager.GetString("CarrinhosDisponiveis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Carrinho.CriarCarrinhoDessinc
        ///
        ////*
        ///	Declare @Parametros varchar(max) = &apos;{&quot;Produtos&quot;:[&quot;1&quot;, &quot;2&quot;],&quot;Login&quot;:&quot;gsilv17&quot;}&apos;
        ///--*/
        ///
        ///Declare @Produtos as table (Produto varchar(50))
        ///Declare @Login varchar(10), @IdCarrinho int
        ///
        ///Insert Into @Produtos
        ///	Select Produto From
        ///		openjson(@Parametros) with (
        ///			Produtos nvarchar(max) &apos;$.Produtos&apos; as json
        ///		)
        ///		Outer Apply openjson(Produtos) with (
        ///			Produto varchar(50) &apos;$&apos;
        ///		);
        ///
        ///Select @Login = [Login] From
        ///	openjson(@Parametros) with (
        ///		[Login] varchar( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CriarCarrinhoDessinc {
            get {
                return ResourceManager.GetString("CriarCarrinhoDessinc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Carrinho - CriarCarrinhoNovo
        ///
        ////*
        ///	Declare @Login varchar(10) = &apos;gsilv17&apos;, @Guid varchar(60) = &apos;ffdc44aec31749f3ac6a9ae860e0d945&apos;
        ///--*/
        ///
        ///Declare 
        ///	@IdCarrinho int,
        ///	@DhCriacao datetime,
        ///	@Matric varchar(10),
        ///	@Campos varchar(max),
        ///	@Query nvarchar(max),
        ///	@Parameters nvarchar(max)
        ///	
        ///Set @DhCriacao = GETDATE()
        ///Select @Matric = LoginSad From TSamsF3User Where [Login] = @Login
        ///
        ///-- Criação do Carrinho
        ///Insert Into Carrinho ( [Login], DhCriacao, CodOrigem, Dessinc ) Values (@Login, @DhCriacao, &apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CriarCarrinhoNovo {
            get {
                return ResourceManager.GetString("CriarCarrinhoNovo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Carrinho - CriarCarrinhoSad
        ///
        ////*
        ///Declare @Login varchar(10), @CodSistema varchar(10)
        ///--*/
        ///
        ///Declare 
        ///	@IdCarrinho int,
        ///	@DhCriacao datetime
        ///
        ///Set @DhCriacao = GETDATE()
        ///
        ///-- Criação do Carrinho
        ///Insert Into Carrinho ( [Login], DhCriacao, CodOrigem, Dessinc, CodSistema ) Values (@Login, @DhCriacao, &apos;Sad&apos;, 0, @CodSistema)
        ///Select @IdCarrinho = @@IDENTITY
        ///
        ///-- Retorno do carrinho criado
        ///Select @IdCarrinho as IdCarrinho.
        /// </summary>
        internal static string CriarCarrinhoSad {
            get {
                return ResourceManager.GetString("CriarCarrinhoSad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select
        ///	  ci.item_nbr as [Código do item SAM&apos;S]
        ///	, ci.item1_desc as [Descrição do item]
        ///	, u.[Login]	as [Login de rede]
        ///	, u.Nome	as [Nome do usuário]
        ///	, u.[LoginSad]	as [Matrícula SAD]
        ///	, c.IdCarrinho	as [Carrinho]
        ///	, ci.ValidacaoTemplate	as [Crítica de validação]
        ///	, ci.DhUltimaImportacaoTemplate as [Data da crítica]
        ///	, ci.vendor_nbr as [Código do Vendor (6 digitos)]
        ///	, ci.codCategoria as [Código da Categoria]
        ///	, ci.descrCategoria as [Descrição da Categoria]
        ///	, ci.codSubcategoria as [Código da  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DownloadCardCarrinho {
            get {
                return ResourceManager.GetString("DownloadCardCarrinho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Carrinho.DownloadCardComCross        ///        ///Select         ///	p.ITEM_NBR				as [Código do Item SAM&apos;S]        ///	, x.SAD_CODPRODU		as [Código do Produto]        ///	, p.Descr				as [Descrição do item]        ///	, x.Sams_Vendor_Nbr		as [Vendor Number]        ///	, x.SAD_CODIGO_EAN		as [Ean]        ///	, x.Upc_Real			as [UPC Real]        ///	, i.Plu_nbr				as [PLU]        ///	, x.QtdePack			as [Pack]        ///	, Case         ///		When ISNULL(x.MULTIPACK, &apos;&apos;) = &apos;N&apos; Then         ///			&apos;Não&apos;         ///		Else         ///			&apos;Sim&apos;         ///	End						as [Multipack]        ///	, i.item_type_code		as [Tipo Item]        ///	, Case         ///		When ISNULL(ci.Ra, &apos;&apos;) = &apos;&apos; Or ci.Ra = &apos;N&apos; The [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DownloadCardComCross {
            get {
                return ResourceManager.GetString("DownloadCardComCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select
        ///	  p.ITEM_NBR 		  as [Código do item SAM&apos;S]
        ///	, p.Descr 			  as [Descrição do item]
        ///	, t.vendor_nbr		  as [Código do Vendor (6 digitos)]
        ///	, t.descrVendor		  as [Descrição do vendor (nome)]
        ///	, t.codCategoria	  as [Código da Categoria]
        ///	, t.descrCategoria	  as [Descrição da Categoria]
        ///	, t.codSubcategoria	  as [Código da Subcategoria]
        ///	, t.descrSubcategoria as [Descrição da sub categoria]
        ///From 
        ///	SAD_ITEM_PRATELEIRA as p
        ///	Inner Join ItemTransformado as t on p.item_nbr = t.item_nbr
        ///	Left  Join [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DownloadCardCross {
            get {
                return ResourceManager.GetString("DownloadCardCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///;with
        ///cteDhUltimoEnvio as ( 
        ///	select 
        ///		cil.IdCarrinhoItem,
        ///		MAX(DhEnvio) as DhUltimoEnvio
        ///	From 
        ///		CarrinhoItemLote as cil
        ///		Inner Join Lote as l on l.IdLote = cil.IdLote
        ///	Where
        ///		DhEnvio &gt;= &apos;2021-04-13&apos;
        ///	Group By
        ///		cil.IdCarrinhoItem
        ///),
        ///cteUltimoRetorno as (
        ///	Select
        ///		cil.*
        ///	From
        ///		CarrinhoItemLote as cil
        ///		Inner Join Lote as l 
        ///			on l.IdLote = cil.IdLote
        ///		Inner Join cteDhUltimoEnvio as ur 
        ///			on ur.DhUltimoEnvio = l.DhEnvio 
        ///			And ur.IdCarrinhoItem = cil.IdCarrinhoItem
        ///	Where [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DownloadCardErroRetorno {
            get {
                return ResourceManager.GetString("DownloadCardErroRetorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Carrinho ItensCarrinhoDisponivel
        ////*
        ///	Declare
        ///		@IdCarrinho int = 890
        ///--*/
        ///
        ///SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
        ///
        ///Select Distinct
        ///	ci.IdCarrinhoItem
        ///	, ci.item_nbr
        ///	, ci.item1_desc
        ///	, codCategoria
        ///	, DescrCategoria
        ///	, codSubcategoria
        ///	, DescrSubCategoria
        ///	, vendor_nbr
        ///	, DescrVendor
        ///	, ci.produto_nbr
        ///	, Case When CodOrigem = &apos;Sad&apos; Then &apos;Sad&apos; Else &apos;Sams&apos; End as CodOrigem
        ///	, ci.Secao
        ///	, ci.Linha
        ///	, ci.Slinha as Sublinha
        ///	, e.N4SAD_SECAO as SecaoDesc
        ///	, e.N5SAD_LINHA as Li [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItensCarrinhoDisponivel {
            get {
                return ResourceManager.GetString("ItensCarrinhoDisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * From Carrinho Where IdCarrinho = @IdCarrinho.
        /// </summary>
        internal static string ObterCarrinho {
            get {
                return ResourceManager.GetString("ObterCarrinho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Carrinho ObterCarrinhoItemEnvio
        ///
        ////*
        ///		Declare @IdCarrinho int = 7
        ///--*/
        ///
        ///Select
        ///	*
        ///From
        ///	CarrinhoItem as ci
        ///Where
        ///	ci.IdCarrinho = @IdCarrinho
        ///	And ci.EmEdicao = 1
        ///	And Not Exists ( select top 1 1 From CarrinhoItem Where IdCarrinho = @IdCarrinho And DhUltimaImportacaoTemplate is null And EmEdicao = 1 )	.
        /// </summary>
        internal static string ObterCarrinhoItemEnvio {
            get {
                return ResourceManager.GetString("ObterCarrinhoItemEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Carrinho ObterContagensCardHome
        ///
        ///Declare @QtdSemDexPara int, @QtdComDexPara int, @QtdItens int, @QtdRetornoErroSad int, @QtdRetornoOkSad int, @QtdRetornoSad int, @QtdCarrinhoItens int, @QtdCarrinhoItensErro int
        ///Declare @PercentSemDexPara numeric(5,2), @PercentComDexPara numeric(5,2), @PercentRetornoErroSad numeric(5,2), @PercentCarrinhoItensErro numeric(5,2)
        ///
        ///Select -- Contagem de itens na prateleira.
        ///	@QtdItens = Count(1)
        ///From 
        ///	SAD_ITEM_PRATELEIRA as p
        ///	Inner Join ItemTransformado as t on p.it [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObterContagemCardHome {
            get {
                return ResourceManager.GetString("ObterContagemCardHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Carrinho - ObterEdicao
        ///
        ////*
        ///	Declare
        ///		@login varchar(10) = &apos;gsilv17&apos;
        ///--*/
        ///
        ///Select 
        ///	*
        ///From
        ///	Carrinho as c
        ///Where
        ///	[login] = @login
        ///	And isnull(Dessinc, 0) = 0.
        /// </summary>
        internal static string ObterEdicao {
            get {
                return ResourceManager.GetString("ObterEdicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Carrinho.ObterExportacao
        ///
        ////*
        ///	Declare @IdCarrinho int = 696
        ///--*/
        ///
        ///SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
        ///
        ///Declare @CodOrigem varchar(5)
        ///
        ///Select @CodOrigem = CodOrigem From Carrinho Where IdCarrinho = @IdCarrinho
        ///
        ///IF @CodOrigem = &apos;Sams&apos; -- Ações sobre a Cross
        ///	Begin
        ///
        ///	Update CarrinhoItem Set -- Regra 2 - Possui cross item ou possui cross upc sem multipack.					
        ///		produto_nbr =
        ///			Case 
        ///				When xItem.XREF_BR_IF_ITEM_ID is not null Or xUpc.MULTIPACK = &apos;N&apos; Or xUpc.MULTIPACK = &apos;&apos;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObterExportacao {
            get {
                return ResourceManager.GetString("ObterExportacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Carrinho PesquisaGestaoCarrinho
        ////*
        ///	Declare @filtro varchar(4000) = &apos;{&quot;Itens&quot;:[],&quot;Produtos&quot;:[],&quot;Usuario&quot;:&quot;gsilv17&quot;}&apos;
        ///--*/
        ///
        ///Declare @Itens as table (item bigint)
        ///Declare @Produtos as table (produtoNbr bigint)
        ///Declare @qtdItemUpc int, @qtdProdutos int
        ///Declare @Usuario varchar(100)
        ///
        ///Insert Into @Itens
        ///	Select item From
        ///		openjson(@filtro) with (
        ///			itens nvarchar(max) &apos;$.Itens&apos; as json
        ///		)
        ///		Outer Apply openjson(itens) with (
        ///			item bigint &apos;$&apos;
        ///		);
        ///	
        ///Insert Into @Produtos
        ///	Select produt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PesquisarGestaoCarrinho {
            get {
                return ResourceManager.GetString("PesquisarGestaoCarrinho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Carrinho.RemoverCarrinhoItem
        ///
        ////*
        ///	Declare @IdCarrinhItem int = 16, @Login varchar(10)
        ///--*/
        ///
        ///Update CarrinhoItem Set 
        ///	EmEdicao = 0, 
        ///	LoginAlteracaoEmEdicao = Case When @Login = &apos;&apos; Then Null Else @Login End, 
        ///	DhUltimaAlteracao = GETDATE() 
        ///Where 
        ///	IdCarrinhoItem = @IdCarrinhoItem.
        /// </summary>
        internal static string RemoverCarrinhoItem {
            get {
                return ResourceManager.GetString("RemoverCarrinhoItem", resourceCulture);
            }
        }
    }
}
