/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CarrinhoItem
	DROP CONSTRAINT FK_CarrinhoItem_LoadTSams
GO
ALTER TABLE dbo.LoadTSams SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Tmp_CarrinhoItem
	(
	IdCarrinhoItem int NOT NULL IDENTITY (1, 1),
	IdCarrinho int NOT NULL,
	IdLoad int NULL,
	DhSelecionado datetime NOT NULL,
	EmEdicao bit NOT NULL,
	DhUltimaExportacaoTemplate datetime NULL,
	DhUltimaImportacaoTemplate datetime NULL,
	item_nbr int NULL,
	vendor_nbr int NULL,
	descrVendor varchar(300) NULL,
	codCategoria int NULL,
	descrCategoria varchar(300) NULL,
	codSubcategoria int NULL,
	descrSubcategoria varchar(300) NULL,
	codFineline int NULL,
	descrFineline varchar(300) NULL,
	ValidacaoTemplate varchar(4000) NULL,
	CriticaSAD varchar(255) NULL,
	upc_original varchar(15) NULL,
	SamsCodDepartamento int NULL,
	SamsDescrDepartamento varchar(50) NULL,
	DescrSecao varchar(50) NULL,
	DescrLinha varchar(50) NULL,
	DescrSublinha varchar(50) NULL,
	Acao varchar(1) NULL,
	TipoProc varchar(1) NULL,
	produto_nbr varchar(13) NULL,
	Emplg varchar(3) NULL,
	Matric varchar(7) NULL,
	item1_desc varchar(35) NULL,
	Descsinal varchar(50) NULL,
	Marc varchar(10) NULL,
	Secao varchar(4) NULL,
	Linha varchar(3) NULL,
	Slinha varchar(3) NULL,
	Itemsim varchar(8) NULL,
	Comp varchar(4) NULL,
	Embc varchar(3) NULL,
	Conv varchar(7) NULL,
	Embv varchar(3) NULL,
	Larg varchar(4) NULL,
	Altu varchar(4) NULL,
	Peso varchar(8) NULL,
	Pesoliq varchar(12) NULL,
	Pesouv varchar(7) NULL,
	Pesome varchar(1) NULL,
	Tpeso varchar(1) NULL,
	Tean varchar(2) NULL,
	Cean varchar(13) NULL,
	Eandg varchar(2) NULL,
	Multpk varchar(1) NULL,
	Upcr varchar(13) NULL,
	Upcrdg varchar(2) NULL,
	Teaneb varchar(2) NULL,
	Ceaneb varchar(15) NULL,
	Mulean varchar(1) NULL,
	Ceantel varchar(13) NULL,
	Eandgtel varchar(2) NULL,
	Qtdinemb varchar(10) NULL,
	Tprod varchar(1) NULL,
	Ra varchar(1) NULL,
	Oimpo varchar(3) NULL,
	Lbranc varchar(1) NULL,
	Kprom varchar(1) NULL,
	Refb varchar(13) NULL,
	Categ varchar(1) NULL,
	Comis varchar(1) NULL,
	Restv varchar(1) NULL,
	Identf varchar(12) NULL,
	Tidentf varchar(1) NULL,
	Edi varchar(1) NULL,
	Cvalid varchar(1) NULL,
	ValProd varchar(4) NULL,
	Medtp varchar(1) NULL,
	Tmed varchar(1) NULL,
	Clasfis varchar(15) NULL,
	Clasipi varchar(5) NULL,
	TelVend varchar(1) NULL,
	cdarea varchar(3) NULL,
	Tamp varchar(8) NULL,
	Unidp varchar(3) NULL,
	Qtdep varchar(4) NULL,
	Tref varchar(8) NULL,
	Uref varchar(3) NULL,
	Vigpcr varchar(1) NULL,
	Dtvprc varchar(7) NULL,
	Pprc varchar(10) NULL,
	Dscprc varchar(5) NULL,
	Bofprc varchar(5) NULL,
	Cpmprc varchar(1) NULL,
	Trnprc varchar(5) NULL,
	Tdeprc varchar(1) NULL,
	Vdeprc varchar(9) NULL,
	Tipiprc varchar(1) NULL,
	Vipiprc varchar(9) NULL,
	Tfrcprc varchar(1) NULL,
	Vfrcprc varchar(9) NULL,
	Tevtprc varchar(1) NULL,
	Vevtprc varchar(9) NULL,
	Tipieprc varchar(1) NULL,
	Vipieprc varchar(9) NULL,
	Tfrtprc varchar(1) NULL,
	Vfrtprc varchar(9) NULL,
	Opcpfl_1 varchar(1) NULL,
	Filpfl_1 varchar(5) NULL,
	Marpfl_1 varchar(6) NULL,
	Fornpfl_1 varchar(8) NULL,
	Locpfl_1 varchar(2) NULL,
	Imppfl_1 varchar(1) NULL,
	Ufpfl_1 varchar(2) NULL,
	Ntpfl_1 varchar(2) NULL,
	Sazpfl_1 varchar(1) NULL,
	Sbgpfl_1 varchar(1) NULL,
	Sitpfl_1 varchar(1) NULL,
	Susppfl_1 varchar(1) NULL,
	Msuppfl_1 varchar(3) NULL,
	Claspfl_1 varchar(1) NULL,
	Cestpfl_1 varchar(1) NULL,
	Cmpupfl_1 varchar(1) NULL,
	Referpfl_1 varchar(15) NULL,
	Opcpfl_2 varchar(1) NULL,
	Filpfl_2 varchar(5) NULL,
	Marpfl_2 varchar(6) NULL,
	Fornpfl_2 varchar(8) NULL,
	Locpfl_2 varchar(2) NULL,
	Imppfl_2 varchar(1) NULL,
	Ufpfl_2 varchar(2) NULL,
	Ntpfl_2 varchar(2) NULL,
	Sazpfl_2 varchar(1) NULL,
	Sbgpfl_2 varchar(1) NULL,
	Sitpfl_2 varchar(1) NULL,
	Susppfl_2 varchar(1) NULL,
	Msuppfl_2 varchar(3) NULL,
	Claspfl_2 varchar(1) NULL,
	Cestpfl_2 varchar(1) NULL,
	Cmpupfl_2 varchar(1) NULL,
	Referpfl_2 varchar(15) NULL,
	Opcpfl_3 varchar(1) NULL,
	Filpfl_3 varchar(5) NULL,
	Marpfl_3 varchar(6) NULL,
	Fornpfl_3 varchar(8) NULL,
	Locpfl_3 varchar(2) NULL,
	Imppfl_3 varchar(1) NULL,
	Ufpfl_3 varchar(2) NULL,
	Ntpfl_3 varchar(2) NULL,
	Sazpfl_3 varchar(1) NULL,
	Sbgpfl_3 varchar(1) NULL,
	Sitpfl_3 varchar(1) NULL,
	Susppfl_3 varchar(1) NULL,
	Msuppfl_3 varchar(3) NULL,
	Claspfl_3 varchar(1) NULL,
	Cestpfl_3 varchar(1) NULL,
	Cmpupfl_3 varchar(1) NULL,
	Referpfl_3 varchar(15) NULL,
	Opcpfl_4 varchar(1) NULL,
	Filpfl_4 varchar(5) NULL,
	Marpfl_4 varchar(6) NULL,
	Fornpfl_4 varchar(8) NULL,
	Locpfl_4 varchar(2) NULL,
	Imppfl_4 varchar(1) NULL,
	Ufpfl_4 varchar(2) NULL,
	Ntpfl_4 varchar(2) NULL,
	Sazpfl_4 varchar(1) NULL,
	Sbgpfl_4 varchar(1) NULL,
	Sitpfl_4 varchar(1) NULL,
	Susppfl_4 varchar(1) NULL,
	Msuppfl_4 varchar(3) NULL,
	Claspfl_4 varchar(1) NULL,
	Cestpfl_4 varchar(1) NULL,
	Cmpupfl_4 varchar(1) NULL,
	Referpfl_4 varchar(15) NULL,
	Opcpfl_5 varchar(1) NULL,
	Filpfl_5 varchar(5) NULL,
	Marpfl_5 varchar(6) NULL,
	Fornpfl_5 varchar(8) NULL,
	Locpfl_5 varchar(2) NULL,
	Imppfl_5 varchar(1) NULL,
	Ufpfl_5 varchar(2) NULL,
	Ntpfl_5 varchar(2) NULL,
	Sazpfl_5 varchar(1) NULL,
	Sbgpfl_5 varchar(1) NULL,
	Sitpfl_5 varchar(1) NULL,
	Susppfl_5 varchar(1) NULL,
	Msuppfl_5 varchar(3) NULL,
	Claspfl_5 varchar(1) NULL,
	Cestpfl_5 varchar(1) NULL,
	Cmpupfl_5 varchar(1) NULL,
	Referpfl_5 varchar(15) NULL,
	Opcpfl_6 varchar(1) NULL,
	Filpfl_6 varchar(5) NULL,
	Marpfl_6 varchar(6) NULL,
	Fornpfl_6 varchar(8) NULL,
	Locpfl_6 varchar(2) NULL,
	Imppfl_6 varchar(1) NULL,
	Ufpfl_6 varchar(2) NULL,
	Ntpfl_6 varchar(2) NULL,
	Sazpfl_6 varchar(1) NULL,
	Sbgpfl_6 varchar(1) NULL,
	Sitpfl_6 varchar(1) NULL,
	Susppfl_6 varchar(1) NULL,
	Msuppfl_6 varchar(3) NULL,
	Claspfl_6 varchar(1) NULL,
	Cestpfl_6 varchar(1) NULL,
	Cmpupfl_6 varchar(1) NULL,
	Referpfl_6 varchar(15) NULL,
	Opcpfl_7 varchar(1) NULL,
	Filpfl_7 varchar(5) NULL,
	Marpfl_7 varchar(6) NULL,
	Fornpfl_7 varchar(8) NULL,
	Locpfl_7 varchar(2) NULL,
	Imppfl_7 varchar(1) NULL,
	Ufpfl_7 varchar(2) NULL,
	Ntpfl_7 varchar(2) NULL,
	Sazpfl_7 varchar(1) NULL,
	Sbgpfl_7 varchar(1) NULL,
	Sitpfl_7 varchar(1) NULL,
	Susppfl_7 varchar(1) NULL,
	Msuppfl_7 varchar(3) NULL,
	Claspfl_7 varchar(1) NULL,
	Cestpfl_7 varchar(1) NULL,
	Cmpupfl_7 varchar(1) NULL,
	Referpfl_7 varchar(15) NULL,
	Opcpfl_8 varchar(1) NULL,
	Filpfl_8 varchar(5) NULL,
	Marpfl_8 varchar(6) NULL,
	Fornpfl_8 varchar(8) NULL,
	Locpfl_8 varchar(2) NULL,
	Imppfl_8 varchar(1) NULL,
	Ufpfl_8 varchar(2) NULL,
	Ntpfl_8 varchar(2) NULL,
	Sazpfl_8 varchar(1) NULL,
	Sbgpfl_8 varchar(1) NULL,
	Sitpfl_8 varchar(1) NULL,
	Susppfl_8 varchar(1) NULL,
	Msuppfl_8 varchar(3) NULL,
	Claspfl_8 varchar(1) NULL,
	Cestpfl_8 varchar(1) NULL,
	Cmpupfl_8 varchar(1) NULL,
	Referpfl_8 varchar(15) NULL,
	Opcpfl_9 varchar(1) NULL,
	Filpfl_9 varchar(5) NULL,
	Marpfl_9 varchar(6) NULL,
	Fornpfl_9 varchar(8) NULL,
	Locpfl_9 varchar(2) NULL,
	Imppfl_9 varchar(1) NULL,
	Ufpfl_9 varchar(2) NULL,
	Ntpfl_9 varchar(2) NULL,
	Sazpfl_9 varchar(1) NULL,
	Sbgpfl_9 varchar(1) NULL,
	Sitpfl_9 varchar(1) NULL,
	Susppfl_9 varchar(1) NULL,
	Msuppfl_9 varchar(3) NULL,
	Claspfl_9 varchar(1) NULL,
	Cestpfl_9 varchar(1) NULL,
	Cmpupfl_9 varchar(1) NULL,
	Referpfl_9 varchar(15) NULL,
	Opcpfl_10 varchar(1) NULL,
	Filpfl_10 varchar(5) NULL,
	Marpfl_10 varchar(6) NULL,
	Fornpfl_10 varchar(8) NULL,
	Locpfl_10 varchar(2) NULL,
	Imppfl_10 varchar(1) NULL,
	Ufpfl_10 varchar(2) NULL,
	Ntpfl_10 varchar(2) NULL,
	Sazpfl_10 varchar(1) NULL,
	Sbgpfl_10 varchar(1) NULL,
	Sitpfl_10 varchar(1) NULL,
	Susppfl_10 varchar(1) NULL,
	Msuppfl_10 varchar(3) NULL,
	Claspfl_10 varchar(1) NULL,
	Cestpfl_10 varchar(1) NULL,
	Cmpupfl_10 varchar(1) NULL,
	Referpfl_10 varchar(15) NULL,
	Opcpfl_11 varchar(1) NULL,
	Filpfl_11 varchar(5) NULL,
	Marpfl_11 varchar(6) NULL,
	Fornpfl_11 varchar(8) NULL,
	Locpfl_11 varchar(2) NULL,
	Imppfl_11 varchar(1) NULL,
	Ufpfl_11 varchar(2) NULL,
	Ntpfl_11 varchar(2) NULL,
	Sazpfl_11 varchar(1) NULL,
	Sbgpfl_11 varchar(1) NULL,
	Sitpfl_11 varchar(1) NULL,
	Susppfl_11 varchar(1) NULL,
	Msuppfl_11 varchar(3) NULL,
	Claspfl_11 varchar(1) NULL,
	Cestpfl_11 varchar(1) NULL,
	Cmpupfl_11 varchar(1) NULL,
	Referpfl_11 varchar(15) NULL,
	Opcpfl_12 varchar(1) NULL,
	Filpfl_12 varchar(5) NULL,
	Marpfl_12 varchar(6) NULL,
	Fornpfl_12 varchar(8) NULL,
	Locpfl_12 varchar(2) NULL,
	Imppfl_12 varchar(1) NULL,
	Ufpfl_12 varchar(2) NULL,
	Ntpfl_12 varchar(2) NULL,
	Sazpfl_12 varchar(1) NULL,
	Sbgpfl_12 varchar(1) NULL,
	Sitpfl_12 varchar(1) NULL,
	Susppfl_12 varchar(1) NULL,
	Msuppfl_12 varchar(3) NULL,
	Claspfl_12 varchar(1) NULL,
	Cestpfl_12 varchar(1) NULL,
	Cmpupfl_12 varchar(1) NULL,
	Referpfl_12 varchar(15) NULL,
	Opcpfl_13 varchar(1) NULL,
	Filpfl_13 varchar(5) NULL,
	Marpfl_13 varchar(6) NULL,
	Fornpfl_13 varchar(8) NULL,
	Locpfl_13 varchar(2) NULL,
	Imppfl_13 varchar(1) NULL,
	Ufpfl_13 varchar(2) NULL,
	Ntpfl_13 varchar(2) NULL,
	Sazpfl_13 varchar(1) NULL,
	Sbgpfl_13 varchar(1) NULL,
	Sitpfl_13 varchar(1) NULL,
	Susppfl_13 varchar(1) NULL,
	Msuppfl_13 varchar(3) NULL,
	Claspfl_13 varchar(1) NULL,
	Cestpfl_13 varchar(1) NULL,
	Cmpupfl_13 varchar(1) NULL,
	Referpfl_13 varchar(15) NULL,
	Opcpfl_14 varchar(1) NULL,
	Filpfl_14 varchar(5) NULL,
	Marpfl_14 varchar(6) NULL,
	Fornpfl_14 varchar(8) NULL,
	Locpfl_14 varchar(2) NULL,
	Imppfl_14 varchar(1) NULL,
	Ufpfl_14 varchar(2) NULL,
	Ntpfl_14 varchar(2) NULL,
	Sazpfl_14 varchar(1) NULL,
	Sbgpfl_14 varchar(1) NULL,
	Sitpfl_14 varchar(1) NULL,
	Susppfl_14 varchar(1) NULL,
	Msuppfl_14 varchar(3) NULL,
	Claspfl_14 varchar(1) NULL,
	Cestpfl_14 varchar(1) NULL,
	Cmpupfl_14 varchar(1) NULL,
	Referpfl_14 varchar(15) NULL,
	Opcpfl_15 varchar(1) NULL,
	Filpfl_15 varchar(5) NULL,
	Marpfl_15 varchar(6) NULL,
	Fornpfl_15 varchar(8) NULL,
	Locpfl_15 varchar(2) NULL,
	Imppfl_15 varchar(1) NULL,
	Ufpfl_15 varchar(2) NULL,
	Ntpfl_15 varchar(2) NULL,
	Sazpfl_15 varchar(1) NULL,
	Sbgpfl_15 varchar(1) NULL,
	Sitpfl_15 varchar(1) NULL,
	Susppfl_15 varchar(1) NULL,
	Msuppfl_15 varchar(3) NULL,
	Claspfl_15 varchar(1) NULL,
	Cestpfl_15 varchar(1) NULL,
	Cmpupfl_15 varchar(1) NULL,
	Referpfl_15 varchar(15) NULL,
	Opcpfl_16 varchar(1) NULL,
	Filpfl_16 varchar(5) NULL,
	Marpfl_16 varchar(6) NULL,
	Fornpfl_16 varchar(8) NULL,
	Locpfl_16 varchar(2) NULL,
	Imppfl_16 varchar(1) NULL,
	Ufpfl_16 varchar(2) NULL,
	Ntpfl_16 varchar(2) NULL,
	Sazpfl_16 varchar(1) NULL,
	Sbgpfl_16 varchar(1) NULL,
	Sitpfl_16 varchar(1) NULL,
	Susppfl_16 varchar(1) NULL,
	Msuppfl_16 varchar(3) NULL,
	Claspfl_16 varchar(1) NULL,
	Cestpfl_16 varchar(1) NULL,
	Cmpupfl_16 varchar(1) NULL,
	Referpfl_16 varchar(15) NULL,
	Opcpfl_17 varchar(1) NULL,
	Filpfl_17 varchar(5) NULL,
	Marpfl_17 varchar(6) NULL,
	Fornpfl_17 varchar(8) NULL,
	Locpfl_17 varchar(2) NULL,
	Imppfl_17 varchar(1) NULL,
	Ufpfl_17 varchar(2) NULL,
	Ntpfl_17 varchar(2) NULL,
	Sazpfl_17 varchar(1) NULL,
	Sbgpfl_17 varchar(1) NULL,
	Sitpfl_17 varchar(1) NULL,
	Susppfl_17 varchar(1) NULL,
	Msuppfl_17 varchar(3) NULL,
	Claspfl_17 varchar(1) NULL,
	Cestpfl_17 varchar(1) NULL,
	Cmpupfl_17 varchar(1) NULL,
	Referpfl_17 varchar(15) NULL,
	Opcpfl_18 varchar(1) NULL,
	Filpfl_18 varchar(5) NULL,
	Marpfl_18 varchar(6) NULL,
	Fornpfl_18 varchar(8) NULL,
	Locpfl_18 varchar(2) NULL,
	Imppfl_18 varchar(1) NULL,
	Ufpfl_18 varchar(2) NULL,
	Ntpfl_18 varchar(2) NULL,
	Sazpfl_18 varchar(1) NULL,
	Sbgpfl_18 varchar(1) NULL,
	Sitpfl_18 varchar(1) NULL,
	Susppfl_18 varchar(1) NULL,
	Msuppfl_18 varchar(3) NULL,
	Claspfl_18 varchar(1) NULL,
	Cestpfl_18 varchar(1) NULL,
	Cmpupfl_18 varchar(1) NULL,
	Referpfl_18 varchar(15) NULL,
	Opcpfl_19 varchar(1) NULL,
	Filpfl_19 varchar(5) NULL,
	Marpfl_19 varchar(6) NULL,
	Fornpfl_19 varchar(8) NULL,
	Locpfl_19 varchar(2) NULL,
	Imppfl_19 varchar(1) NULL,
	Ufpfl_19 varchar(2) NULL,
	Ntpfl_19 varchar(2) NULL,
	Sazpfl_19 varchar(1) NULL,
	Sbgpfl_19 varchar(1) NULL,
	Sitpfl_19 varchar(1) NULL,
	Susppfl_19 varchar(1) NULL,
	Msuppfl_19 varchar(3) NULL,
	Claspfl_19 varchar(1) NULL,
	Cestpfl_19 varchar(1) NULL,
	Cmpupfl_19 varchar(1) NULL,
	Referpfl_19 varchar(15) NULL,
	Opcpfl_20 varchar(1) NULL,
	Filpfl_20 varchar(5) NULL,
	Marpfl_20 varchar(6) NULL,
	Fornpfl_20 varchar(8) NULL,
	Locpfl_20 varchar(2) NULL,
	Imppfl_20 varchar(1) NULL,
	Ufpfl_20 varchar(2) NULL,
	Ntpfl_20 varchar(2) NULL,
	Sazpfl_20 varchar(1) NULL,
	Sbgpfl_20 varchar(1) NULL,
	Sitpfl_20 varchar(1) NULL,
	Susppfl_20 varchar(1) NULL,
	Msuppfl_20 varchar(3) NULL,
	Claspfl_20 varchar(1) NULL,
	Cestpfl_20 varchar(1) NULL,
	Cmpupfl_20 varchar(1) NULL,
	Referpfl_20 varchar(15) NULL,
	Opcpfl_21 varchar(1) NULL,
	Filpfl_21 varchar(5) NULL,
	Marpfl_21 varchar(6) NULL,
	Fornpfl_21 varchar(8) NULL,
	Locpfl_21 varchar(2) NULL,
	Imppfl_21 varchar(1) NULL,
	Ufpfl_21 varchar(2) NULL,
	Ntpfl_21 varchar(2) NULL,
	Sazpfl_21 varchar(1) NULL,
	Sbgpfl_21 varchar(1) NULL,
	Sitpfl_21 varchar(1) NULL,
	Susppfl_21 varchar(1) NULL,
	Msuppfl_21 varchar(3) NULL,
	Claspfl_21 varchar(1) NULL,
	Cestpfl_21 varchar(1) NULL,
	Cmpupfl_21 varchar(1) NULL,
	Referpfl_21 varchar(15) NULL,
	Opcpfl_22 varchar(1) NULL,
	Filpfl_22 varchar(5) NULL,
	Marpfl_22 varchar(6) NULL,
	Fornpfl_22 varchar(8) NULL,
	Locpfl_22 varchar(2) NULL,
	Imppfl_22 varchar(1) NULL,
	Ufpfl_22 varchar(2) NULL,
	Ntpfl_22 varchar(2) NULL,
	Sazpfl_22 varchar(1) NULL,
	Sbgpfl_22 varchar(1) NULL,
	Sitpfl_22 varchar(1) NULL,
	Susppfl_22 varchar(1) NULL,
	Msuppfl_22 varchar(3) NULL,
	Claspfl_22 varchar(1) NULL,
	Cestpfl_22 varchar(1) NULL,
	Cmpupfl_22 varchar(1) NULL,
	Referpfl_22 varchar(15) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_CarrinhoItem SET (LOCK_ESCALATION = TABLE)
GO
SET IDENTITY_INSERT dbo.Tmp_CarrinhoItem ON
GO
IF EXISTS(SELECT * FROM dbo.CarrinhoItem)
	 EXEC('INSERT INTO dbo.Tmp_CarrinhoItem (IdCarrinhoItem, IdCarrinho, IdLoad, DhSelecionado, EmEdicao, DhUltimaExportacaoTemplate, DhUltimaImportacaoTemplate, item_nbr, vendor_nbr, descrVendor, codCategoria, descrCategoria, codSubcategoria, descrSubcategoria, codFineline, descrFineline, ValidacaoTemplate, CriticaSAD, upc_original, SamsCodDepartamento, SamsDescrDepartamento, DescrSecao, DescrLinha, DescrSublinha, Acao, TipoProc, produto_nbr, Emplg, Matric, item1_desc, Descsinal, Marc, Secao, Linha, Slinha, Itemsim, Comp, Embc, Conv, Embv, Larg, Altu, Peso, Pesoliq, Pesouv, Pesome, Tpeso, Tean, Cean, Eandg, Multpk, Upcr, Upcrdg, Teaneb, Ceaneb, Mulean, Ceantel, Eandgtel, Qtdinemb, Tprod, Ra, Oimpo, Lbranc, Kprom, Refb, Categ, Comis, Restv, Identf, Tidentf, Edi, Cvalid, ValProd, Medtp, Tmed, Clasfis, Clasipi, TelVend, cdarea, Tamp, Unidp, Qtdep, Tref, Uref, Vigpcr, Dtvprc, Pprc, Dscprc, Bofprc, Cpmprc, Trnprc, Tdeprc, Vdeprc, Tipiprc, Vipiprc, Tfrcprc, Vfrcprc, Tevtprc, Vevtprc, Tipieprc, Vipieprc, Tfrtprc, Vfrtprc, Opcpfl_1, Filpfl_1, Marpfl_1, Fornpfl_1, Locpfl_1, Imppfl_1, Ufpfl_1, Ntpfl_1, Sazpfl_1, Sbgpfl_1, Sitpfl_1, Susppfl_1, Msuppfl_1, Claspfl_1, Cestpfl_1, Cmpupfl_1, Referpfl_1, Opcpfl_2, Filpfl_2, Marpfl_2, Fornpfl_2, Locpfl_2, Imppfl_2, Ufpfl_2, Ntpfl_2, Sazpfl_2, Sbgpfl_2, Sitpfl_2, Susppfl_2, Msuppfl_2, Claspfl_2, Cestpfl_2, Cmpupfl_2, Referpfl_2, Opcpfl_3, Filpfl_3, Marpfl_3, Fornpfl_3, Locpfl_3, Imppfl_3, Ufpfl_3, Ntpfl_3, Sazpfl_3, Sbgpfl_3, Sitpfl_3, Susppfl_3, Msuppfl_3, Claspfl_3, Cestpfl_3, Cmpupfl_3, Referpfl_3, Opcpfl_4, Filpfl_4, Marpfl_4, Fornpfl_4, Locpfl_4, Imppfl_4, Ufpfl_4, Ntpfl_4, Sazpfl_4, Sbgpfl_4, Sitpfl_4, Susppfl_4, Msuppfl_4, Claspfl_4, Cestpfl_4, Cmpupfl_4, Referpfl_4, Opcpfl_5, Filpfl_5, Marpfl_5, Fornpfl_5, Locpfl_5, Imppfl_5, Ufpfl_5, Ntpfl_5, Sazpfl_5, Sbgpfl_5, Sitpfl_5, Susppfl_5, Msuppfl_5, Claspfl_5, Cestpfl_5, Cmpupfl_5, Referpfl_5, Opcpfl_6, Filpfl_6, Marpfl_6, Fornpfl_6, Locpfl_6, Imppfl_6, Ufpfl_6, Ntpfl_6, Sazpfl_6, Sbgpfl_6, Sitpfl_6, Susppfl_6, Msuppfl_6, Claspfl_6, Cestpfl_6, Cmpupfl_6, Referpfl_6, Opcpfl_7, Filpfl_7, Marpfl_7, Fornpfl_7, Locpfl_7, Imppfl_7, Ufpfl_7, Ntpfl_7, Sazpfl_7, Sbgpfl_7, Sitpfl_7, Susppfl_7, Msuppfl_7, Claspfl_7, Cestpfl_7, Cmpupfl_7, Referpfl_7, Opcpfl_8, Filpfl_8, Marpfl_8, Fornpfl_8, Locpfl_8, Imppfl_8, Ufpfl_8, Ntpfl_8, Sazpfl_8, Sbgpfl_8, Sitpfl_8, Susppfl_8, Msuppfl_8, Claspfl_8, Cestpfl_8, Cmpupfl_8, Referpfl_8, Opcpfl_9, Filpfl_9, Marpfl_9, Fornpfl_9, Locpfl_9, Imppfl_9, Ufpfl_9, Ntpfl_9, Sazpfl_9, Sbgpfl_9, Sitpfl_9, Susppfl_9, Msuppfl_9, Claspfl_9, Cestpfl_9, Cmpupfl_9, Referpfl_9, Opcpfl_10, Filpfl_10, Marpfl_10, Fornpfl_10, Locpfl_10, Imppfl_10, Ufpfl_10, Ntpfl_10, Sazpfl_10, Sbgpfl_10, Sitpfl_10, Susppfl_10, Msuppfl_10, Claspfl_10, Cestpfl_10, Cmpupfl_10, Referpfl_10, Opcpfl_11, Filpfl_11, Marpfl_11, Fornpfl_11, Locpfl_11, Imppfl_11, Ufpfl_11, Ntpfl_11, Sazpfl_11, Sbgpfl_11, Sitpfl_11, Susppfl_11, Msuppfl_11, Claspfl_11, Cestpfl_11, Cmpupfl_11, Referpfl_11, Opcpfl_12, Filpfl_12, Marpfl_12, Fornpfl_12, Locpfl_12, Imppfl_12, Ufpfl_12, Ntpfl_12, Sazpfl_12, Sbgpfl_12, Sitpfl_12, Susppfl_12, Msuppfl_12, Claspfl_12, Cestpfl_12, Cmpupfl_12, Referpfl_12, Opcpfl_13, Filpfl_13, Marpfl_13, Fornpfl_13, Locpfl_13, Imppfl_13, Ufpfl_13, Ntpfl_13, Sazpfl_13, Sbgpfl_13, Sitpfl_13, Susppfl_13, Msuppfl_13, Claspfl_13, Cestpfl_13, Cmpupfl_13, Referpfl_13, Opcpfl_14, Filpfl_14, Marpfl_14, Fornpfl_14, Locpfl_14, Imppfl_14, Ufpfl_14, Ntpfl_14, Sazpfl_14, Sbgpfl_14, Sitpfl_14, Susppfl_14, Msuppfl_14, Claspfl_14, Cestpfl_14, Cmpupfl_14, Referpfl_14, Opcpfl_15, Filpfl_15, Marpfl_15, Fornpfl_15, Locpfl_15, Imppfl_15, Ufpfl_15, Ntpfl_15, Sazpfl_15, Sbgpfl_15, Sitpfl_15, Susppfl_15, Msuppfl_15, Claspfl_15, Cestpfl_15, Cmpupfl_15, Referpfl_15, Opcpfl_16, Filpfl_16, Marpfl_16, Fornpfl_16, Locpfl_16, Imppfl_16, Ufpfl_16, Ntpfl_16, Sazpfl_16, Sbgpfl_16, Sitpfl_16, Susppfl_16, Msuppfl_16, Claspfl_16, Cestpfl_16, Cmpupfl_16, Referpfl_16, Opcpfl_17, Filpfl_17, Marpfl_17, Fornpfl_17, Locpfl_17, Imppfl_17, Ufpfl_17, Ntpfl_17, Sazpfl_17, Sbgpfl_17, Sitpfl_17, Susppfl_17, Msuppfl_17, Claspfl_17, Cestpfl_17, Cmpupfl_17, Referpfl_17, Opcpfl_18, Filpfl_18, Marpfl_18, Fornpfl_18, Locpfl_18, Imppfl_18, Ufpfl_18, Ntpfl_18, Sazpfl_18, Sbgpfl_18, Sitpfl_18, Susppfl_18, Msuppfl_18, Claspfl_18, Cestpfl_18, Cmpupfl_18, Referpfl_18, Opcpfl_19, Filpfl_19, Marpfl_19, Fornpfl_19, Locpfl_19, Imppfl_19, Ufpfl_19, Ntpfl_19, Sazpfl_19, Sbgpfl_19, Sitpfl_19, Susppfl_19, Msuppfl_19, Claspfl_19, Cestpfl_19, Cmpupfl_19, Referpfl_19, Opcpfl_20, Filpfl_20, Marpfl_20, Fornpfl_20, Locpfl_20, Imppfl_20, Ufpfl_20, Ntpfl_20, Sazpfl_20, Sbgpfl_20, Sitpfl_20, Susppfl_20, Msuppfl_20, Claspfl_20, Cestpfl_20, Cmpupfl_20, Referpfl_20, Opcpfl_21, Filpfl_21, Marpfl_21, Fornpfl_21, Locpfl_21, Imppfl_21, Ufpfl_21, Ntpfl_21, Sazpfl_21, Sbgpfl_21, Sitpfl_21, Susppfl_21, Msuppfl_21, Claspfl_21, Cestpfl_21, Cmpupfl_21, Referpfl_21, Opcpfl_22, Filpfl_22, Marpfl_22, Fornpfl_22, Locpfl_22, Imppfl_22, Ufpfl_22, Ntpfl_22, Sazpfl_22, Sbgpfl_22, Sitpfl_22, Susppfl_22, Msuppfl_22, Claspfl_22, Cestpfl_22, Cmpupfl_22, Referpfl_22)
		SELECT IdCarrinhoItem, IdCarrinho, IdLoad, DhSelecionado, EmEdicao, DhUltimaExportacaoTemplate, DhUltimaImportacaoTemplate, item_nbr, vendor_nbr, descrVendor, codCategoria, descrCategoria, codSubcategoria, descrSubcategoria, codFineline, descrFineline, ValidacaoTemplate, CriticaSAD, upc_original, SamsCodDepartamento, SamsDescrDepartamento, DescrSecao, DescrLinha, DescrSublinha, Acao, TipoProc, produto_nbr, Emplg, Matric, item1_desc, Descsinal, Marc, Secao, Linha, Slinha, Itemsim, Comp, Embc, Conv, Embv, Larg, Altu, Peso, Pesoliq, Pesouv, Pesome, Tpeso, Tean, Cean, Eandg, Multpk, Upcr, Upcrdg, Teaneb, Ceaneb, Mulean, Ceantel, Eandgtel, Qtdinemb, Tprod, Ra, Oimpo, Lbranc, Kprom, Refb, Categ, Comis, Restv, Identf, Tidentf, Edi, Cvalid, ValProd, Medtp, Tmed, Clasfis, Clasipi, TelVend, cdarea, Tamp, Unidp, Qtdep, Tref, Uref, Vigpcr, Dtvprc, Pprc, Dscprc, Bofprc, Cpmprc, Trnprc, Tdeprc, Vdeprc, Tipiprc, Vipiprc, Tfrcprc, Vfrcprc, Tevtprc, Vevtprc, Tipieprc, Vipieprc, Tfrtprc, Vfrtprc, Opcpfl_1, Filpfl_1, Marpfl_1, Fornpfl_1, Locpfl_1, Imppfl_1, Ufpfl_1, Ntpfl_1, Sazpfl_1, Sbgpfl_1, Sitpfl_1, Susppfl_1, Msuppfl_1, Claspfl_1, Cestpfl_1, Cmpupfl_1, Referpfl_1, Opcpfl_2, Filpfl_2, Marpfl_2, Fornpfl_2, Locpfl_2, Imppfl_2, Ufpfl_2, Ntpfl_2, Sazpfl_2, Sbgpfl_2, Sitpfl_2, Susppfl_2, Msuppfl_2, Claspfl_2, Cestpfl_2, Cmpupfl_2, Referpfl_2, Opcpfl_3, Filpfl_3, Marpfl_3, Fornpfl_3, Locpfl_3, Imppfl_3, Ufpfl_3, Ntpfl_3, Sazpfl_3, Sbgpfl_3, Sitpfl_3, Susppfl_3, Msuppfl_3, Claspfl_3, Cestpfl_3, Cmpupfl_3, Referpfl_3, Opcpfl_4, Filpfl_4, Marpfl_4, Fornpfl_4, Locpfl_4, Imppfl_4, Ufpfl_4, Ntpfl_4, Sazpfl_4, Sbgpfl_4, Sitpfl_4, Susppfl_4, Msuppfl_4, Claspfl_4, Cestpfl_4, Cmpupfl_4, Referpfl_4, Opcpfl_5, Filpfl_5, Marpfl_5, Fornpfl_5, Locpfl_5, Imppfl_5, Ufpfl_5, Ntpfl_5, Sazpfl_5, Sbgpfl_5, Sitpfl_5, Susppfl_5, Msuppfl_5, Claspfl_5, Cestpfl_5, Cmpupfl_5, Referpfl_5, Opcpfl_6, Filpfl_6, Marpfl_6, Fornpfl_6, Locpfl_6, Imppfl_6, Ufpfl_6, Ntpfl_6, Sazpfl_6, Sbgpfl_6, Sitpfl_6, Susppfl_6, Msuppfl_6, Claspfl_6, Cestpfl_6, Cmpupfl_6, Referpfl_6, Opcpfl_7, Filpfl_7, Marpfl_7, Fornpfl_7, Locpfl_7, Imppfl_7, Ufpfl_7, Ntpfl_7, Sazpfl_7, Sbgpfl_7, Sitpfl_7, Susppfl_7, Msuppfl_7, Claspfl_7, Cestpfl_7, Cmpupfl_7, Referpfl_7, Opcpfl_8, Filpfl_8, Marpfl_8, Fornpfl_8, Locpfl_8, Imppfl_8, Ufpfl_8, Ntpfl_8, Sazpfl_8, Sbgpfl_8, Sitpfl_8, Susppfl_8, Msuppfl_8, Claspfl_8, Cestpfl_8, Cmpupfl_8, Referpfl_8, Opcpfl_9, Filpfl_9, Marpfl_9, Fornpfl_9, Locpfl_9, Imppfl_9, Ufpfl_9, Ntpfl_9, Sazpfl_9, Sbgpfl_9, Sitpfl_9, Susppfl_9, Msuppfl_9, Claspfl_9, Cestpfl_9, Cmpupfl_9, Referpfl_9, Opcpfl_10, Filpfl_10, Marpfl_10, Fornpfl_10, Locpfl_10, Imppfl_10, Ufpfl_10, Ntpfl_10, Sazpfl_10, Sbgpfl_10, Sitpfl_10, Susppfl_10, Msuppfl_10, Claspfl_10, Cestpfl_10, Cmpupfl_10, Referpfl_10, Opcpfl_11, Filpfl_11, Marpfl_11, Fornpfl_11, Locpfl_11, Imppfl_11, Ufpfl_11, Ntpfl_11, Sazpfl_11, Sbgpfl_11, Sitpfl_11, Susppfl_11, Msuppfl_11, Claspfl_11, Cestpfl_11, Cmpupfl_11, Referpfl_11, Opcpfl_12, Filpfl_12, Marpfl_12, Fornpfl_12, Locpfl_12, Imppfl_12, Ufpfl_12, Ntpfl_12, Sazpfl_12, Sbgpfl_12, Sitpfl_12, Susppfl_12, Msuppfl_12, Claspfl_12, Cestpfl_12, Cmpupfl_12, Referpfl_12, Opcpfl_13, Filpfl_13, Marpfl_13, Fornpfl_13, Locpfl_13, Imppfl_13, Ufpfl_13, Ntpfl_13, Sazpfl_13, Sbgpfl_13, Sitpfl_13, Susppfl_13, Msuppfl_13, Claspfl_13, Cestpfl_13, Cmpupfl_13, Referpfl_13, Opcpfl_14, Filpfl_14, Marpfl_14, Fornpfl_14, Locpfl_14, Imppfl_14, Ufpfl_14, Ntpfl_14, Sazpfl_14, Sbgpfl_14, Sitpfl_14, Susppfl_14, Msuppfl_14, Claspfl_14, Cestpfl_14, Cmpupfl_14, Referpfl_14, Opcpfl_15, Filpfl_15, Marpfl_15, Fornpfl_15, Locpfl_15, Imppfl_15, Ufpfl_15, Ntpfl_15, Sazpfl_15, Sbgpfl_15, Sitpfl_15, Susppfl_15, Msuppfl_15, Claspfl_15, Cestpfl_15, Cmpupfl_15, Referpfl_15, Opcpfl_16, Filpfl_16, Marpfl_16, Fornpfl_16, Locpfl_16, Imppfl_16, Ufpfl_16, Ntpfl_16, Sazpfl_16, Sbgpfl_16, Sitpfl_16, Susppfl_16, Msuppfl_16, Claspfl_16, Cestpfl_16, Cmpupfl_16, Referpfl_16, Opcpfl_17, Filpfl_17, Marpfl_17, Fornpfl_17, Locpfl_17, Imppfl_17, Ufpfl_17, Ntpfl_17, Sazpfl_17, Sbgpfl_17, Sitpfl_17, Susppfl_17, Msuppfl_17, Claspfl_17, Cestpfl_17, Cmpupfl_17, Referpfl_17, Opcpfl_18, Filpfl_18, Marpfl_18, Fornpfl_18, Locpfl_18, Imppfl_18, Ufpfl_18, Ntpfl_18, Sazpfl_18, Sbgpfl_18, Sitpfl_18, Susppfl_18, Msuppfl_18, Claspfl_18, Cestpfl_18, Cmpupfl_18, Referpfl_18, Opcpfl_19, Filpfl_19, Marpfl_19, Fornpfl_19, Locpfl_19, Imppfl_19, Ufpfl_19, Ntpfl_19, Sazpfl_19, Sbgpfl_19, Sitpfl_19, Susppfl_19, Msuppfl_19, Claspfl_19, Cestpfl_19, Cmpupfl_19, Referpfl_19, Opcpfl_20, Filpfl_20, Marpfl_20, Fornpfl_20, Locpfl_20, Imppfl_20, Ufpfl_20, Ntpfl_20, Sazpfl_20, Sbgpfl_20, Sitpfl_20, Susppfl_20, Msuppfl_20, Claspfl_20, Cestpfl_20, Cmpupfl_20, Referpfl_20, Opcpfl_21, Filpfl_21, Marpfl_21, Fornpfl_21, Locpfl_21, Imppfl_21, Ufpfl_21, Ntpfl_21, Sazpfl_21, Sbgpfl_21, Sitpfl_21, Susppfl_21, Msuppfl_21, Claspfl_21, Cestpfl_21, Cmpupfl_21, Referpfl_21, Opcpfl_22, Filpfl_22, Marpfl_22, Fornpfl_22, Locpfl_22, Imppfl_22, Ufpfl_22, Ntpfl_22, Sazpfl_22, Sbgpfl_22, Sitpfl_22, Susppfl_22, Msuppfl_22, Claspfl_22, Cestpfl_22, Cmpupfl_22, Referpfl_22 FROM dbo.CarrinhoItem WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_CarrinhoItem OFF
GO
ALTER TABLE dbo.CarrinhoItemLote
	DROP CONSTRAINT FK_CarrinhoItemLote_CarrinhoItem
GO
DROP TABLE dbo.CarrinhoItem
GO
EXECUTE sp_rename N'dbo.Tmp_CarrinhoItem', N'CarrinhoItem', 'OBJECT' 
GO
ALTER TABLE dbo.CarrinhoItem ADD CONSTRAINT
	PK_CarrinhoItem PRIMARY KEY CLUSTERED 
	(
	IdCarrinhoItem
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
CREATE NONCLUSTERED INDEX IX_CarrinhoItem_item_nbr ON dbo.CarrinhoItem
	(
	item_nbr
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_CarrinhoItem_produto_nbr ON dbo.CarrinhoItem
	(
	produto_nbr
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.CarrinhoItem ADD CONSTRAINT
	FK_CarrinhoItem_LoadTSams FOREIGN KEY
	(
	IdLoad
	) REFERENCES dbo.LoadTSams
	(
	IdLoad
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CarrinhoItemLote ADD CONSTRAINT
	FK_CarrinhoItemLote_CarrinhoItem FOREIGN KEY
	(
	IdCarrinhoItem
	) REFERENCES dbo.CarrinhoItem
	(
	IdCarrinhoItem
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CarrinhoItemLote SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
