//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apcm.Service.EstruturaMercadologica {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EstruturaMercadologicaScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EstruturaMercadologicaScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apcm.Service.EstruturaMercadologica.EstruturaMercadologicaScripts", typeof(EstruturaMercadologicaScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Distinct         ///	N4SAD_SECAOID		as Secao        ///	, N4SAD_SECAO		as SecaoDesc        ///	, N5SAD_LINHAID		as Linha        ///	, N5SAD_LINHA		as LinhaDesc        ///	, N6SAD_SUBLINHAID	as Sublinha        ///	, N6SAD_SUBLINHA	as SublinhaDesc        ///From         ///	IF_HIERARCHY_XREF_SAMS.
        /// </summary>
        internal static string ObterEstruturaSad {
            get {
                return ResourceManager.GetString("ObterEstruturaSad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 
        ///	CodCategoria
        ///	, DescrCategoria
        ///	, CodSubcategoria
        ///	, DescrSubcategoria
        ///	, CodFineline
        ///	, DescrFineline
        ///From 
        ///	EstruturaMercadologica .
        /// </summary>
        internal static string ObterEstruturaSams {
            get {
                return ResourceManager.GetString("ObterEstruturaSams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Distinct N5SAD_LINHAID as Linha, Convert(varchar, N5SAD_LINHAID) + &apos; - &apos; + N5SAD_LINHA as LinhaDesc From IF_HIERARCHY_XREF_SAMS Where N4SAD_SECAOID = @Secao Order By 1.
        /// </summary>
        internal static string ObterLinhas {
            get {
                return ResourceManager.GetString("ObterLinhas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Distinct N4SAD_SECAOID as Secao, Convert(varchar, N4SAD_SECAOID) + &apos; - &apos; + N4SAD_SECAO as SecaoDesc From IF_HIERARCHY_XREF_SAMS Order By 1.
        /// </summary>
        internal static string ObterSecoes {
            get {
                return ResourceManager.GetString("ObterSecoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Distinct N6SAD_SUBLINHAID as Sublinha, Convert(varchar, N6SAD_SUBLINHAID) + &apos; - &apos; + N6SAD_SUBLINHA as SublinhaDesc From IF_HIERARCHY_XREF_SAMS Where N4SAD_SECAOID = @Secao And N5SAD_LINHAID = @Linha Order By 1.
        /// </summary>
        internal static string ObterSublinhas {
            get {
                return ResourceManager.GetString("ObterSublinhas", resourceCulture);
            }
        }
    }
}
