//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apcm.TSamsF1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apcm.TSamsF1.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * From {0} Where IdLoad = 0.
        /// </summary>
        internal static string BulkTable {
            get {
                return ResourceManager.GetString("BulkTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update loadTSams Set dhF1Fim = GETDATE(), F1Resultado = @p0 where idLoad = @p1.
        /// </summary>
        internal static string EncerrarLoad {
            get {
                return ResourceManager.GetString("EncerrarLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update logTSamsF1 Set dhFim = GETDATE(), resultado = @p0, registros = @p1 Where idLog = @p2.
        /// </summary>
        internal static string FinalizarLog {
            get {
                return ResourceManager.GetString("FinalizarLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Into loadTSams (dhF1Inicio) values (GetDate())
        ///Select @@IDENTITY as idLoad.
        /// </summary>
        internal static string IniciarLoad {
            get {
                return ResourceManager.GetString("IniciarLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Into logTSamsF1 (idLoad, entidade, dhInicio) Values (@p0, @p1, GETDATE())
        ///Select @@IDENTITY as idLog.
        /// </summary>
        internal static string IniciarLog {
            get {
                return ResourceManager.GetString("IniciarLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truncate Table {0}.
        /// </summary>
        internal static string Limpar {
            get {
                return ResourceManager.GetString("Limpar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete
        ///	a
        ///From
        ///	{0} as a
        ///	Inner Join {0} as b on 
        ///		a.idLoad &lt; b.idLoad
        ///		And a.{1} &lt; b.{1}
        ///		{2}
        ///Where
        ///	b.idLoad = @p0.
        /// </summary>
        internal static string RemoverAntigos {
            get {
                return ResourceManager.GetString("RemoverAntigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		And a.{0} = b.{0} 
        ///.
        /// </summary>
        internal static string RemoverAntigosFiltro {
            get {
                return ResourceManager.GetString("RemoverAntigosFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count(*) as qtd.
        /// </summary>
        internal static string SelectCount {
            get {
                return ResourceManager.GetString("SelectCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select {0} From {1}.{2} {3} Where 1=1 {4} {5}
        ///-- 0: * / Count
        ///-- 1: schema
        ///-- 2: nome
        ///-- 3: Join
        ///-- 4: filtro
        ///-- 5: data atualizacao.
        /// </summary>
        internal static string SelectMain {
            get {
                return ResourceManager.GetString("SelectMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM (
        ///	SELECT ROW_NUMBER() OVER (ORDER BY {0}) AS ROW_NUMBER, b.* FROM (
        ///		{1}
        ///	) AS b
        ///) AS a WHERE a.ROW_NUMBER &gt; {2} AND a.ROW_NUMBER &lt;= {3}.
        /// </summary>
        internal static string SelectPage {
            get {
                return ResourceManager.GetString("SelectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And CAST({0} AS VARCHAR(26)) &gt; ?.
        /// </summary>
        internal static string SelectWhereNew {
            get {
                return ResourceManager.GetString("SelectWhereNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///-- Último load
        ///Declare @idLoad int
        ///Select @idLoad = Max(idLoad) From loadTSams Where dhF1Fim is not null
        ///if(@idLoad is null) return
        ///
        ///
        ///Update loadTSams set dhF2Inicio = GETDATE(), dhF2Fim = null, f2Resultado = null where idLoad = @idLoad
        ///
        ///
        ///Declare @nome varchar(50), @ordemExec varchar(30), @registros int, @resultado varchar(4000)
        ///Declare @idLogTSamsF2 int
        ///Set @resultado = &apos;&apos;;
        ///Declare cursorTransformacao Cursor For Select nome, ordemExec From Transformacoes Where ativa = 1 Order By ordemExec asc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TSamsF2 {
            get {
                return ResourceManager.GetString("TSamsF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare @last_update_ts datetime2 = null 
        ///Select Top 1 @last_update_ts = Max({0}) From {1}
        ///Select @last_update_ts = isnull(@last_update_ts, convert(datetime, &apos;1900-01-01&apos;))
        ///Select Format(@last_update_ts, &apos;yyyy-MM-dd-HH.mm.ss.ffffff&apos;) as last_update_ts.
        /// </summary>
        internal static string UltimaAtualizacaoFormat {
            get {
                return ResourceManager.GetString("UltimaAtualizacaoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Valor From ParametrosTSamsF1 Where Nome = &apos;LoadInicial&apos;.
        /// </summary>
        internal static string VerificarLoadInicial {
            get {
                return ResourceManager.GetString("VerificarLoadInicial", resourceCulture);
            }
        }
    }
}
